### ISSUE TITLE
Hello, I am the author of qq,weibo,wechat client.

### ISSUE THREAD

**Issue by yujiandong** [yiisoft/yii2-authclient#103]
https://github.com/yujiandong/yii2-authclient

I wrote the qq,weibo,wechat client for yii 7 months ago, and added it to github 6 months ago.

**Comment by xutongle** [comment]
是在你的基础上修改的，也同样是MIT协议发行

**Comment by yujiandong** [comment]
You dont change any codes. So you can not change the author

**Comment by xutongle** [comment]
你最好查一下scope 代码段，和样式表图像

**Comment by xutongle** [comment]
另外如果你觉得不合适，就自己fork代码该回去合并

**Comment by xutongle** [comment]
这个代码是从一个项目里扣出来的，所以我不知道原作者

**Comment by yujiandong** [comment]
这个借口好！

**Comment by xutongle** [comment]
https://github.com/xjflyttp/yii2-oauth/blob/master/WeiboAuth.php

**Comment by xutongle** [comment]
我也不认可你是原作者，都是Yii标准出来的代码，Oauth2.0接口

**Comment by zfan67** [comment]
不明真相的群众强势围观，楼下有木有达人简单科普一下究竟神马是MIT协议

**Comment by ThomasZJ** [comment]
Just a reminder that globalization is one of the beauties, and enablers, of open source.

**Comment by XGowe** [comment]
- 问题一： 
  - "*是在你的基础上修改的，也同样是MIT协议发行，我只是做了你没做的，就是合并到官方库。^_^*"
  - "*这个代码是从一个项目里扣出来的，所以我不知道原作者*"
  - **这两句话存在矛盾之处。**
- 问题二 :
  - MIT 许可协议中写明： "*The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.*" (https://github.com/yujiandong/yii2-authclient/blob/master/LICENSE.md)
  - 即：“*在软件和软件的所有副本中都必须包含以上版权声明和本许可声明。*” (https://zh.wikipedia.org/wiki/MIT%E8%A8%B1%E5%8F%AF%E8%AD%89#.E8.A2.AB.E6.8E.88.E6.AC.8A.E4.BA.BA.E7.BE.A9.E5.8B.99)
  - 因此，请不要拿 MIT 许可协议当作挡箭牌，因为**你已经违反了 MIT 许可协议**。

**Comment by cnhx** [comment]
支持原作者 @yujiandong

**Comment by yujiandong** [comment]
oauth是有接口，但是怎么实现是各有各的方法的。
可以拿别人的作为参考，但一定要自己写。

**Comment by raincious** [comment]
It's pretty weird to see someone who believe who can own other people's project just by changing few CSS file and add few icons.

I do that to my Gnome all the time, does that means I'm the author of Gnome + so can change it's copyright declaration? I don't think so.

**Comment by registe** [comment]
[MIT License](http://opensource.org/licenses/mit-license.html)...

**Comment by xutongle** [comment]
说过了，代码来自一个已有项目，改项目没有引用你的composer，无任何注释版权声明，我只是按照yii的约定加上了相关说明，在你发起投诉后后对比知道原作者是你，我认为该代码来自你的项目这是后来知道的，如果不尊重你的版权我也不会跟你扯这么多。依照各接口的sdk，和yii的约定规范就是写出雷同的代码也没有什么奇怪的。而且github里也有人的代码比你的还要早，我能说你那个人才是原作者吗？

发自我的 iPhone

**Comment by yujiandong** [comment]
yii有标准，是没错，也就只要写几个方法。
因此写出来的代码雷同很正常。
但是几乎一模一样就说不过去了。

**Comment by yujiandong** [comment]
能承认这一点很好。也没别的意思，希望以后能多注意点。

**Comment by xutongle** [comment]
我也说明了，并不知道原作者，我拿到手的是一个商业项目，无注释，我做的只是按yii约定添加注释和文档，提取出有用的文件，合并到官方库，刚开始也说过了，对于这点我不在解释说明，而且本次合并只是为了方便使用，无其他意图。

发自我的 iPhone

**Comment by XGowe** [comment]
@xutongle
- 这不是我的项目，如果你想指的是“该项目”“作者”，请不要直接引用我的话，因为这可能导致误解；谢谢。
- 我不认为你对别人质疑的回应的过程，是和别人“扯”。
- 你的回复中提到的 “composer” 是指什么？
- “改项目没有引用你的composer，无任何注释版权声明”（我默认这里是“该”，做后续回复）：对一个没有“任何注释版权声明”的“项目”，直接“来自”，并且加上许可文件，我没有看出你对他人版权的尊重，更何况是一个“商业项目”。
- 请至少在发现问题之后，遵循 MIT 许可协议内容，完善你的当前项目中的许可文件；如果你遵循了 MIT 许可协议，那就没有什么可以指摘的。

**Comment by int64ago** [comment]
@xutongle 

Please don't add `发自我的 iPhone`, it's disgusting!

**Comment by coderzuo** [comment]
既然已经知道原作者了，那就赶快改许可文件呗，不改光扯皮有啥意思啊

**Comment by raincious** [comment]
Say SORRY is usually easier than LIE.

For example:
How do a person who claims he "had no idea who are the original AUTHOR of those code", change the AUTHOR declaration with that incredible precision?

https://github.com/yiisoft/yii2-authclient/pull/102/files#diff-3c3d4d78edbd84e52d3e1a5b2c0a9fa8R41
https://github.com/yujiandong/yii2-authclient/blob/master/Qq.php#L35

**Comment by cebe** [comment]
Thanks for bringing this to our attention, I have removed the commit from master for now. Need some time to keep up with the comments.

**Comment by imcaffrey** [comment]
@cebe 
You can find some deleted comments [here](http://v2ex.com/t/274400).

**Comment by samdark** [comment]
@yujiandong sorry about that. I haven't thought someone will do that and haven't checked authorship precisely.

**Comment by Denniskevin** [comment]
支持原作者

**Comment by cebe** [comment]
@Denniskevin the problem has already been solved.
