### ISSUE TITLE
Use httpclient library

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2-authclient#108]
In order to fix numerous issues like #27 the sophisticated httpclient library should be used as a background for this extension.

This should be either [yii2-httpclient](https://github.com/yiisoft/yii2-httpclient) or Guzzle.

Depends on:
https://github.com/yiisoft/yii2/issues/2953

**Comment by samdark** [comment]
@klimov-paul are you sure it makes sense to wrap Guzzle with our own library instead of recommending to use it directly in the guide?

**Comment by klimov-paul** [comment]
Resolved via #117
