### ISSUE TITLE
Why Twitter not response user email

### ISSUE THREAD

**Issue by yatskanich** [yiisoft/yii2-authclient#109]
I have enabled to require option email from user while auth in twitter app 
http://joxi.ru/1A55v87HK5P9jA.
But in response not have an emial.
I try add include_email=true to params, as write on twitter docs https://dev.twitter.com/rest/reference/get/account/verify_credentials
but it not take effect

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.8
| PHP version      | 5.5.9
| Operating system | ubuntu

**Comment by samdark** [comment]
You have to request email permissions separately via https://support.twitter.com/forms/platform. It's described at the page you've linked to.
