### ISSUE TITLE
GitHub - hidden email attribute handling

### ISSUE THREAD

**Issue by luke-** [yiisoft/yii2-authclient#111]
Maybe this is also something for the default implementation?

When the email is set to "hidden" at GitHub, you need an additional request to fetch users e-mail.

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/authclient/GitHub.php#L20-L36

**Comment by samdark** [comment]
So you still can get user's email even if it's hidden?

**Comment by samdark** [comment]
If so, it makes perfect sense to have it.

**Comment by luke1-** [comment]
Yes, this is workaround handles especially hidden emails in the public github profile.
You can also test it live on: https://community.humhub.com

**Comment by klimov-paul** [comment]
Resolved by commit a0c075929a5920c7eb949779c878083ea862bd09
