### ISSUE TITLE
Failing to authenticate the user when sending rest post request

### ISSUE THREAD

**Issue by traykovn** [yiisoft/yii2-authclient#112]
I have a rest server and a client both implemented in Yii2. The server needs to authenticate the user in order to return result. The client keeps a database table with access tokens and sends a token with each request:

```
$token = new OAuthToken();
$token->setToken(UserAccount::getToken(Yii::$app->user->id));
$client->setAccessToken($token);        
return $client->api($apiSubUrl, $method, $params, $headers);
```
The server authenticates the user by using the QueryParamAuth:

```
public function behaviors()
{
    $behaviors = parent::behaviors();
    $behaviors['authenticator'] = [
        QueryParamAuth::className(),
    ];
    return $behaviors;
}
```
When I send a GET request, everything works fine, but when I send a post request, the access_token is added by the framework to the post body, not as a get param. This way I cannot authenticate the user.

What I can think of so far is:

- To implement a new authenticator e.g. PostParamAuth, that checks the POST body for access_token param;
- To check whether the request is POST and to add the access_token as a get param;
- To add it to the header (Bearer authenticaton) every time, no matter what type the request is.

My case must have already been implemented by the framework and maybe I am missing something. Please tell me which is the best way that can work out my situation.

**Comment by klimov-paul** [comment]
> when I send a post request, the access_token is added by the framework to the post body, not as a get param

This is expected behavior: `access_token` is a regular request param and thus it is passed as any other request param dpending on request method.

> The server authenticates the user by using the QueryParamAuth

I am afraid this is wrong choice for the OAuth protocol, since it opearates only GET request part.

There is no issue here in the scope of `yii2-authclient`.
Also I can see no issue at `QueryParamAuth`, since its name and documentation says clearly it works only with URL query string.

**Comment by traykovn** [comment]
Ok, then which is the correct way to authenticate the user, when making rest request via yii2-authclient, since there is no authenticator for post params?

**Comment by klimov-paul** [comment]
@traykovn, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by traykovn** [comment]
Ok, thanks!
