### ISSUE TITLE
Document source code url in invalid

### ISSUE THREAD

**Issue by moein7tl** [yiisoft/yii2-authclient#12]
I need to have access to Facebook.php source code ,but by following http://www.yiiframework.com/doc-2.0/yii-authclient-clients-facebook.html and Source Code redirect to github not found page.

**Comment by samdark** [comment]
@cebe that's API generator issue, correct?

**Comment by klimov-paul** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/7871
