### ISSUE TITLE
Can not get "User Access Token" after login ?

### ISSUE THREAD

**Issue by levanlau** [yiisoft/yii2-authclient#125]
### What steps will reproduce the problem?
- I have logined successfully with yii2-authclient, the result have my personal info but "user access token" is not ? I can not find any function get this user access token. With "app access token" and "page access token", i can get them easily.
- I want to get "user access token"
Thank you.
| Q                | A
| ---------------- | ---
| Yii vesion : 2.0.9      |
| PHP version      |
| Operating system |

**Comment by libedux** [comment]
After searching a bit on documents I had found the solution. 
`      $client = Yii::$app->authClientCollection->getClient('google');
        $accessToken = $client->getAccessToken();`
