### ISSUE TITLE
Error from adding tab to page

### ISSUE THREAD

**Issue by levanlau** [yiisoft/yii2-authclient#126]
- While i call api to add tab to page, an error return "Request failed with code: 403, message: A page access token is required to request this resource..."
My code in php :
{
...
$page_id=xxxxxxxx;
$page_access_token="xxxxxxxxxxxxxxxxxxxxxxxxxx...";
$result=$client->api('v2.06/'.$page_id.'/tabs', 'POST', ['app_id'=>xxxx, 'tab'=>'xxxx', 'position'=>3, 'access_token'=>$page_access_token, .....]);
...
}
???
- I don't know where to put "access_token" in the "api" function is true ?
- I use many other api function to call for manage page is successfully.
Please help me. Thank you
| ---------------- | ---
| Yii vesion   : 2.0.9    |

**Comment by klimov-paul** [comment]
@levanlau, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
