### ISSUE TITLE
Request rejected by GitHub with yii2-authclient 2.1.0

### ISSUE THREAD

**Issue by oyyq99999** [yiisoft/yii2-authclient#128]
### What steps will reproduce the problem?
Authorize a GitHub account for the first time(i.e. needs user confirm) with 2.1.0
### What's expected?
Success
### What do you get instead?
Got 403 with this message
>Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.

### Additional info
I have tried 2.0.6 after got this error, and it works well.

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| Authclient version|2.1.0
| PHP version      | 7.0.9
| Operating system | OS X 10.11.6

**Comment by klimov-paul** [comment]
Resolved by commit b3102c81ea694e654781b6adc2aa73b72d7c41c3
