### ISSUE TITLE
fetchRequestToken with configured accessToken fails (invalid signature)

### ISSUE THREAD

**Issue by rhertogh** [yiisoft/yii2-authclient#130]
### What steps will reproduce the problem?

Create a Oauth1 client with an accessToken configured. Eg
`$authClient = new MyOauth1([
               ...
              'accessToken' => [
                    'token' => 'something from cache',
                    'tokenSecret' =>  'something from cache',
                ],
                ...
            ]);`

Call `$authClient->fetchRequestToken()`

### What's expected?

The client fetches a requestToken

### What do you get instead?

A invalid signature error from the third party server

### Additional info

In `fetchRequestToken` (yii\authclient\OAuth1) on line 82 the 'token' state is removed (`$this->removeState('token');`)
Shouldn't it also remove the access token? e.g.  `$this->setAccessToken([]);`
Leaving the access token will cause the `composeSignatureKey` function  use the existing access token to compose the key, I'm not sure if this is expected behavior according to the Oauth1 standard.

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.9
| yii2-authclient version       | 2.1.0
| PHP version      |   5.6
| Operating system | CentOS 7

**Comment by klimov-paul** [comment]
Resolved by commit 843c1150bd9d88d18157bd9881d24b9334201c98
