### ISSUE TITLE
GitHub login doesn't work

### ISSUE THREAD

**Issue by itzen** [yiisoft/yii2-authclient#131]
Trying to login via GitHub results with fallowing exception:

```
Exception – yii\authclient\InvalidResponseException

Request failed with code: 403, message: Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.
```

Bug is related with: https://developer.github.com/v3/#user-agent-required

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| yii2-authclient version	       | 2.1.0
| PHP version      |  7.0.8
| Operating system | Windows 10

**Comment by klimov-paul** [comment]
Duplicates #128
