### ISSUE TITLE
Adding OpenID Connect

### ISSUE THREAD

**Issue by GeorgeGardiner** [yiisoft/yii2-authclient#133]
Hi guys,

I've been working on an OpenIDConnect client (https://github.com/CommonMode/yii2-openidconnect) which I was considering contributing. My concern is the external dependencies it has (for JOSE security) are a little heavy.

Is it worth forking and opening a PR for this, or is it unlikely to be accepted because of this?

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-authclient/pull/113#issuecomment-228361212
