### ISSUE TITLE
Additional params for client

### ISSUE THREAD

**Issue by drSun** [yiisoft/yii2-authclient#134]
Hello! I need to pass additional data for vkontakte client - image_size (to get an original photo, not minified). But I see that in AuthAction class in authOAuth2() method buildAuthUrl() is called without any params. What is the way to solve the problem?

**Comment by klimov-paul** [comment]
@drSun, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
