### ISSUE TITLE
IIS "An item with the same key has already been added."

### ISSUE THREAD

**Issue by mhoogstraten** [yiisoft/yii2-authclient#135]
### What steps will reproduce the problem?
Connecting with an IIS server with oAuth1

### What's expected?
Request token

### What do you get instead?
"An item with the same key has already been added."
`
{
"name": "Exception",
"message": "Request failed with code: 500, message: An item with the same key has already been added.",
"code": 0,
"type": "yii\\authclient\\InvalidResponseException",
"file": "C:\\xampp\\htdocs\\app\\vendor\\yiisoft\\yii2-authclient\\BaseOAuth.php",
"line": 221,
"stack-trace": [
"#0 C:\\xampp\\htdocs\\app\\vendor\\yiisoft\\yii2-authclient\\OAuth1.php(97): yii\\authclient\\BaseOAuth->sendRequest(Object(yii\\httpclient\\Request))",
]
}
`

### Code
`
$requestToken = $this->fetchRequestToken(); //That's all it takes to produce the error
`

### Additional info
It is sending the oAuth tokens also as a content (POST?) response, which producesed: "An item with the same key has already been added."

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.7
| PHP version      | 7.0.2
| Operating system | Windows 10

**Comment by klimov-paul** [comment]
OAuth1 flow works fine for the `Twitter`.
I will be unable to help unless you provide the answers for the following questions:

- Which HTTP request is send at `fetchRequestToken()` in your case?
- Which HTTP request should be sent in order to fetch request token?

**Comment by mhoogstraten** [comment]
Ofcourse;

## Current version (not working for IIS):
`Array
(
    [CURLOPT_USERAGENT] => Test OAuth 1.0 Client
    [CURLOPT_CONNECTTIMEOUT] => 30
    [CURLE_FTP_PORT_FAILED] => 30
    [CURLE_FTP_SSL_FAILED] => 
    [CURLOPT_HTTPHEADER] => Array
        (
            [0] => Content-type: application/x-www-form-urlencoded
            [1] => Authorization: OAuth oauth_consumer_key="KEYHASH", oauth_callback="example.com/oauth", oauth_version="1.0", oauth_nonce="HASHNONCE", oauth_timestamp="1466512000", oauth_signature_method="HMAC-SHA1", oauth_signature="SIGNATUREHASH"
        )
 
    [CURLOPT_RETURNTRANSFER] => 1
    [CURLOPT_URL] => https://example.com/webservices/oauthwebsite/ndsoauthhandler.ashx
    [CURLOPT_POST] => 1
    [CURLOPT_POSTFIELDS] => oauth_consumer_key=MYKEY&oauth_callback=example.com/oauth&oauth_version=1.0&oauth_nonce=123456HASH&oauth_timestamp=1466512000&oauth_signature_method=HMAC-SHA1&oauth_signature=SIGNATUREHASH
)`

## Working (without POST fields and is also working for Twitter):
`
Array
(
    [CURLOPT_USERAGENT] => Test OAuth 1.0 Client
    [CURLOPT_CONNECTTIMEOUT] => 30
    [CURLE_FTP_PORT_FAILED] => 30
    [CURLE_FTP_SSL_FAILED] => 
    [CURLOPT_HTTPHEADER] => Array
        (
            [0] => Content-type: application/x-www-form-urlencoded
            [1] => Authorization: OAuth oauth_consumer_key="KEYHASH", oauth_callback="example.com/oauth", oauth_version="1.0", oauth_nonce="HASHNONCE", oauth_timestamp="1466512000", oauth_signature_method="HMAC-SHA1", oauth_signature="SIGNATUREHASH"
        )
 
    [CURLOPT_RETURNTRANSFER] => 1
    [CURLOPT_URL] => https://example.com/webservices/oauthwebsite/ndsoauthhandler.ashx
    [CURLOPT_POST] => 1
    [CURLOPT_POSTFIELDS] => 
)
`

**Comment by mhoogstraten** [comment]
With POST the headers should always have a ContentLength:
https://tools.ietf.org/html/rfc7230#section-3.3.2

**Comment by klimov-paul** [comment]
> With POST the headers should always have a ContentLength

It is handled automatically.

It is obvious your Oauth provider consider data passed via POST body as duplication of data passed by Authorization header.
There must be some strict check on the server side performed by `.net` library.

**Comment by mhoogstraten** [comment]
This is not an improvement? Because it seems IIS has this by default.
Is there a way i can disable the duplication?

**Comment by klimov-paul** [comment]
I'll need to check the RFC specification about 'fetch access token' request. If it says it should not hold the body - I'll fix the extension. Otherwise you'll have to provide your own implementation of `fetchRequestToken()` for your client class.

**Comment by mhoogstraten** [comment]
Also when i check the ContentLength, there wasn't any. In StreamTransport i debugged $contextOptions; it displays:
`
Array
(
    [http] => Array
        (
            [method] => POST
            [ignore_errors] => 1
            [content] => oauth_version=1.0&oauth_nonce=ASDASDASD&oauth_timestamp=1472630000&oauth_consumer_key=USER&oauth_callback=SOMEURL&oauth_signature_method=HMAC-SHA1&oauth_signature=KEY
            [header] => Array
                (
                    [0] => Authorization: OAuth oauth_version="1.0", oauth_nonce="ASDASDASD", oauth_timestamp="1472600000", oauth_consumer_key="USER", oauth_callback="SOMEURL", oauth_signature_method="HMAC-SHA1", oauth_signature="KEY"
                    [1] => Content-Type: application/x-www-form-urlencoded; charset=UTF-8
                )
            [user_agent] => STUB OAuth 1.0 Client
            [timeout] => 30
        )
    [ssl] => Array
        (
            [verify_peer] => 
        )
)
`

"Content-Type: application/x-www-form-urlencoded; charset=UTF-8"

**Comment by klimov-paul** [comment]
Resolved by commit afcdbad569673f5c9a810ba0c69273eaa4644189

**Comment by harrytang** [comment]
My Yii2 Flickr Auth works fine with yii2-authclient 2.1.1, same problem after update to 2.1.2.

**Comment by harrytang** [comment]
My Flickr Auth works fine with yii2-authclient v2.1.1, same problem after update to 2.1.2

**Comment by samdark** [comment]
@harrytang please open new issue.
