### ISSUE TITLE
OpenId::fetchAxAttributes() incorrectly works with counted attributes

### ISSUE THREAD

**Issue by ruslanbes** [yiisoft/yii2-authclient#140]
I found this problem while testing with the OpenId server that explicitly returns `openid.ax.count.XXXX=1` for all requested ax attributes and sets their values not to `openid.ax.value.XXXX` param but to `openid.ax.value.XXXX.1`. 

I looked the code of the [`OpenId::fetchAxAttributes()`](https://github.com/yiisoft/yii2-authclient/blob/master/OpenId.php#L753) and it seems for me it ignores the "counted" fields at all. 

Suppose we got a fetch_response like the one listed in [specification](https://openid.net/specs/openid-attribute-exchange-1_0.html#fetch_response):

```
openid.ns.ax=http://openid.net/srv/ax/1.0
openid.ax.mode=fetch_response
openid.ax.type.fname=http://example.com/schema/fullname
openid.ax.type.gender=http://example.com/schema/gender
openid.ax.type.fav_dog=http://example.com/schema/favourite_dog
openid.ax.type.fav_movie=http://example.com/schema/favourite_movie
openid.ax.value.fname=John Smith
openid.ax.count.gender=0
openid.ax.value.fav_dog=Spot
openid.ax.count.fav_movie=2
openid.ax.value.fav_movie.1=Movie1
openid.ax.value.fav_movie.2=Movie2
openid.ax.update_url=http://idconsumer.com/update?transaction_id=a6b5c41
```

When `fetchAxAttributes()` starts working it has all these params inside `$this->data` with the exception that dots in keys are replaced with underscores. 

Now the main loop of that function looks for `openid_ax_value_` pattern in keys (Line 775). 

It encounters the `openid_ax_value_fav_movie_1` key and extracts the `$key` as `'fav_movie_1'`. 

Then at the line 786 it looks for `'openid_ax_type_fav_movie_1'` but can't find it - the correct key is `'openid_ax_type_fav_movie'`, so the value would be missing.

is it a bug or am I missing something in the loading step that prevents that?

**Comment by klimov-paul** [comment]
Since no trusted public OpenID povider exists, I can not verify the issue or possible fix for it.
Thus there is no way I can fix it.
OpenID protocol is almost dead, its support will likely be removed in future major version.
