### ISSUE TITLE
Where is?

### ISSUE THREAD

**Issue by vegas0250** [yiisoft/yii2-authclient#143]
Hello, where is clients for mail.ru, and ok.ru? thx.

**Comment by samdark** [comment]
These aren't part of official repository. Check packagist for third-party solutions.

**Comment by vitalyzhakov** [comment]
Hello!

`These aren't part of official repository.`

Why?

We use nodge client, but it is not supported. And have several bugs.

**Comment by samdark** [comment]
> Why?

Because of maintenance cost mainly. It's hard to maintain too many things well and we prefer community to take some and release as extensions.
