### ISSUE TITLE
OAuthToken tokenParamKey

### ISSUE THREAD

**Issue by aleksanderd** [yiisoft/yii2-authclient#144]
### What steps will reproduce the problem?

``` php
        $token = new OAuthToken([
            'token' => 'tokenValue',
            'tokenParamKey' => 'access_token',
        ]);
        echo $token->token ?? 'EMPTY!';
```

it will set `token` using default `tokenParamKey`, then set `tokenParamKey`, and later the getter will not found the token using new key.
### What's expected?

`tokenValue`
### What do you get instead?

`EMPTY!`
### Additional info

In my case I using OAuth2 based client, and tried to create it like this:

``` php
        $client = new SomeOAuth2Client([
            'clientId' => 'id',
            'clientSecret'  => 'secret',
            'accessToken' => [
                'token' => 'tokeValue',
            ],
        ]);
```

and since [OAuth2::createToken()](https://github.com/yiisoft/yii2-authclient/blob/master/OAuth2.php#L202) adds `tokenParamKey` config's parameter, it will be after the `token` parameter.

**Comment by klimov-paul** [comment]
You should swap `tokenParamKey` and `token` at your config - then it will work fine.
I see no reason for the fix of this issue, since there are many places aroung the framework with similar dependencies between parameters.
