### ISSUE TITLE
Unsure about intro of validateAuthState 

### ISSUE THREAD

**Issue by newscloud** [yiisoft/yii2-authclient#147]
### What steps will reproduce the problem?
composer install broke my production facebook login

### What's expected?
It should work

Why did this get added without more notice or clarity? Is there documentation to explain how to support this? I wasn't sure. It broke my code. 

It also seems to have added a migration, I'm kind of confused ... 
`  class m161022_064508_extend_auth_table_for_authorization extends Migration
  {
      public function up()
      {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }
        $this->addColumn('{{%auth}}','oauth_token','string NOT NULL');
        $this->addColumn('{{%auth}}','oauth_token_secret','string NOT NULL');
        $this->addColumn('{{%auth}}','screen_name','string NOT NULL');
        $this->addColumn('{{%auth}}','x_auth_expires',Schema::TYPE_BIGINT. ' NOT NULL DEFAULT 0');`

I tried to fix things with:
`'authClientCollection' => [
              'class' => 'yii\authclient\Collection',
              'clients' => [
                  'facebook' => [
                      'class' => 'yii\authclient\clients\Facebook',
                      'clientId' => $config['oauth_fb_id'],
                      'clientSecret' => $config['oauth_fb_secret'],
                      'validateAuthState' => false,
                  ],
              ],
          ],
`

but then started getting database errors due to the above migration I wasn't aware of.

### What do you get instead?
This exception from OAuth2.php
public function fetchAccessToken($authCode, array $params = [])
    {
        if ($this->validateAuthState) {
            $authState = $this->getState('authState');
            if (!isset($_REQUEST['state']) || empty($authState) || strcmp($_REQUEST['state'], $authState) !== 0) {
                throw new HttpException(400, 'Invalid auth state parameter.');

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by cebe** [comment]
> composer install broke my production facebook login

from which version to which version did you upgrade? 2.0.x -> 2.1.x is considered BC breaking according to https://github.com/yiisoft/yii2/blob/master/docs/internals/versions.md#2x0-major-releases

**Comment by newscloud** [comment]
Hi and thanks for the quick response.

Here's what happened. I had Site A under development and a production install that worked. 
I had to change the git repo definition and redid composer install on production. Suddenly, it broke authentication and messed up my auth db table. Even when I turned off the new csrf setting, Strict MySQL broke code where the new fields were added to the Auth db table.

I'm not a composer expert ... so I don't think I changed anything.
Site A:
"yiisoft/yii2": ">=2.0.10",

My other site is as follows:
Site B:
"yiisoft/yii2": ">=2.0.7",

I'm not quite sure what happened.

**Comment by cebe** [comment]
what would be relevant in this case would be the entry for `yiisoft/yii2-authclient`. you should never require versions via `>=` as that would include 2.1, 3.0, etc which can break your application, use `~2.0.10` or `2.0.*` instead. If you have used `yiisoft/yii2-authclient` version 2.0.x before, make sure you require that in your composer.json:

`"yiisoft/yii2-authclient": "~2.0.0"`

**Comment by newscloud** [comment]
Thank you!
