### ISSUE TITLE
NoConflict mode for the widget inline script

### ISSUE THREAD

**Issue by Ariestattoo** [yiisoft/yii2-authclient#149]
### What steps will reproduce the problem?
When used with PJAX the widget will return the js, but it won't be wrapped in a Document Ready function. The dollar sign implementation conflicts with other libraries and is not defined globally when all assets are compressed. 
### What's expected?
Using jQuery instead of $ on line of 264 of AuthChoice.php will fix this

| Q                | A
| ---------------- | ---
| Yii vesion       |2.10
| PHP version      |7.0
| Operating system |Linux 4.4.0-59-generic #80-Ubuntu SMP  x86_64 GNU/Linux

**Comment by samdark** [comment]
Agree. Could you help us with a pull request?

**Comment by klimov-paul** [comment]
Resolved by commit c6b7c52
