### ISSUE TITLE
Array to string conversion in /widgets/AuthChoice.php (Line: 197)

### ISSUE THREAD

**Issue by alex-wdmg** [yiisoft/yii2-authclient#153]
**Notice:** Array to string conversion.

Yii: /vendor/yiisoft/yii2/helpers/BaseHtml.php
```php
public static function addCssClass(&$options, $class)
    {
        if (isset($options['class'])) {
            $classes = ' ' . $options['class'] . ' ';
            if (strpos($classes, ' ' . $class . ' ') === false) {
                $options['class'] .= ' ' . $class;
            }
        } else {
            $options['class'] = $class;
        }
    }
```

Source: [Html::addCssClass($htmlOptions, ['widget' => 'auth-link']);](https://github.com/yiisoft/yii2-authclient/blob/master/widgets/AuthChoice.php#L197)

_Yii Framework/2.0.5
PHP version  5.6.10
Mac OS X Yosemite 10.10.5 (MAMP)_

**Comment by samdark** [comment]
How to reproduce it?

**Comment by alex-wdmg** [comment]
Х.з., Александр. Вот разбираюсь со старым проектом, там виджет авторизации... обновился до 2.0.12-dev нотик пропал... сейчас откачусь - выложу трейс.

**Comment by samdark** [comment]
Так, если в текущей версии всё в норме, то, получается, баг уже поправлен?

**Comment by alex-wdmg** [comment]
Да, видимо апнулся не до последней версии... с 2.0.12 все ок. Можно закрыть репорт.
