### ISSUE TITLE
yii2-authclient popup

### ISSUE THREAD

**Issue by vickysw** [yiisoft/yii2-authclient#154]
Hi,

In my website, I install the yii2-authclient,  but I have a few issues (I am using facebook,LinkedIn):

when I click on the facebook button it opens a window, 
**problem is that the login is made inside the popup windows that opens. The main window doesn't be refreshed.**
There is any solution for this problems?

I think the popup window should appear and close immediately after the facebook login, and then the main window auto-refresh.
| Yii version       | 2.0

**Comment by anandBarhate** [comment]
Is this issue resolved?
I am having the same issue. After logging in using social login the pop up window does not close and return to main window

**Comment by srakl** [comment]
> Is this issue resolved? I am having the same issue. After logging in using social login the pop up window does not close and return to main window

is it? is there a work around?
