### ISSUE TITLE
Add support for OpenID Connect (OIDC)?

### ISSUE THREAD

**Issue by MarcoMoreno** [yiisoft/yii2-authclient#155]
Are there plans to support [OpenID Connect](http://openid.net/connect/) (aka OIDC)?

OpenID Connect is an authentication layer built on top of the OAuth2 authorization framework.  Now that OIDC has replaced OpenID and is based upon the popular OAuth2 framework, OIDC adoption is growing quickly and poised to become the industry standard for authentication and authorization.

I see that yii2-authclient supports both OpenID and OAuth2 so it should be fairly easy to support OpenID Connect. Unfortunately, I don't have the skills to implement this. There is a third-party extension "[yii2-openidconnect](https://github.com/CommonMode/yii2-openidconnect)", but I'm not sure it is production ready.  Its code may be a good starting point or perhaps it could be merged.

### Some background on OpenID Connect:
- [http://openid.net/connect/](http://openid.net/connect/)
- [http://openid.net/connect/faq/](http://openid.net/connect/faq/)
- [http://en.wikipedia.org/wiki/OpenID_Connect](http://en.wikipedia.org/wiki/OpenID_Connect)

### Some major providers supporting OpenID Connect:
- [Google](https://developers.google.com/identity/protocols/OpenIDConnect)
- [Microsoft Azure](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-openid-connect-code)
- [Amazon Web Services](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html)
- [Ping Identity](https://www.pingidentity.com/en/resources/articles/openid-connect.html)
- [Gigya Identity Management](https://developers.gigya.com/display/GD/OpenID+Connect)
- [Janrain Identity & Access Management](http://www.janrain.com/blog/janrain-supports-openid-connect/) 
- [Gluu Identity & Access Management](https://www.gluu.org/resources/documents/standards/openid-connect/)
- [WSO2 Identity & Access Management](https://docs.wso2.com/display/IS510/OAuth2-OpenID+Connect)
- [ForgeRock Access Management](https://www.forgerock.com/blog/openam-now-openid-certified/)
- [Centrify Identity Server](https://docs.centrify.com/en/centrify/appref/index.html#page/cloudhelp/gen/saas_appref_openid.html)
- [IBM Websphere](https://www.ibm.com/support/knowledgecenter/SSD28V_8.5.5/com.ibm.websphere.wlp.core.doc/ae/cwlp_openid_connect.html)
- [Paypal](https://developer.paypal.com/docs/integration/direct/identity/log-in-with-paypal/)
- [Salesforce](https://developer.salesforce.com/page/Inside_OpenID_Connect_on_Force.com)
- [VMware Authentication Services](https://vmware.github.io/lightwave/)

Note that this started as [a topic on the Yii forums](http://www.yiiframework.com/forum/index.php/topic/74594-support-for-openid-connect-oidc/)

**Comment by klimov-paul** [comment]
I am unsure of the possible implementation.
OpenIdConnect requires verification of the JWS (JSON Web Signature) via JWK. Such process is very complex and it is hard to be implemented from scratch.
The solution can be usage of the JWS dedicated 3rd party library - [Jose](https://github.com/Spomky-Labs/jose), but it creates additnal [heavy dependency](https://github.com/Spomky-Labs/jose/blob/master/composer.json#L27-L39).
However, it seems JWS, JWT becomes ore and more popular over modern authentication flows. It can be it will become mandatory in some future.

I can see following ways:
- create a separated package with `Jose` dependecy as well as `yii2-authclient` 
- include OpenIdConnect  into `yii2-authclient` as well as  `Jose` dependecy
- include OpenIdConnect  into `yii2-authclient`, but make `Jose` optional

I prefer the latest. While protocol demands JWS verification, it actually can be disabled making `Jose` redundant. Introducing separated package, which contains a single relatively simple class, does not seem  good.

**Comment by klimov-paul** [comment]
`Jose` library requires PHP >= 5.6:
https://github.com/Spomky-Labs/jose/blob/master/composer.json#L28

So it can not be included as a mandatory dependency into `yii2-authclient` before major release.

**Comment by samdark** [comment]
Optional dependency sounds OK.

**Comment by klimov-paul** [comment]
Relates #133

**Comment by klimov-paul** [comment]
PR opened #158

**Comment by klimov-paul** [comment]
Resolved by commit a14201bd3384650f89b5516692a2c75301677fae

**Comment by Ziggizag** [comment]
Dear friends,

What about this:

https://github.com/Spomky-Labs/jose

(We highly recommend you to use the new JWT Framework project instead of this library.

    Active support of this library is provided until end of 2018.
    Security support will be provided from 2019 and up to end of 2020.

A migration guide is available in the documentation of the new project.)

**Comment by ScottHuangZL** [comment]
I did not find OIDC client under yii2-authclient/src/clients folder, able find Oauth2Client.php.   Do auth client now able support OIDC? If yes, can you show us a sample, do it use new JWT framework? thanks.

**Comment by ScottHuangZL** [comment]
Successful use OpenIdConnect for GitLab OIDC SSO login.  So, basic function is work.   As for Okta, encounter below error:
**"error":"invalid_dpop_proof","error_description":"The DPoP proof JWT header is missing."**

I will asking the admin tentative disable that request.  **But how Yii2 OpenIdConnect to support 'Demonstrating Proof of Possession" ? Thanks.**
