### ISSUE TITLE
with facebook, the "login" and "username" are"name"

### ISSUE THREAD

**Issue by mourahi** [yiisoft/yii2-authclient#16]
In your controller, the $attributes["login"] and $attributes["username"] doesn't existe . please replace "login" and "username" with "name". 

Thanks

**Comment by samdark** [comment]
Which controller you're referring to exactly?

**Comment by samdark** [comment]
The one in the docs? https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/quick-start.md?

**Comment by samdark** [comment]
If yes, it's for GitHub.

**Comment by mourahi** [comment]
public function onAuthSuccess($client)
    {
       $attributes = $client->getUserAttributes();
   ................

                if (isset($attributes['email']) && isset($attributes['username']) && User::find()->where(['email' => $attributes['email']])->exists()) {
                   ................

                        'username' => $attributes['login'],
                        'email' => $attributes['email'],
                        'password' => $password,
                 ...................

**Comment by samdark** [comment]
Yes, that's GitHub example and it works. For each auth client a set of fields could vary.

**Comment by klimov-paul** [comment]
This is an example code, it can work for all cases.

**Comment by ApeMonkeys** [comment]
Maybe a comment  in the github example would be nice. For me facebook login only worked because I found this site and changed username to name.
