### ISSUE TITLE
[google] BaseOAuth::refreshAccessToken doesn't work.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2-authclient#162]
### What steps will reproduce the problem?
Set up login with Google. Login, get a token. 

### What's expected?
The token has an expiration duration of 3600 (1 hour).
After waiting 1 hour, or manually setting the duration to 1 second, `refreshAccessToken` is called.
I expect it to refresh the token.

### What do you get instead?
A `HTTP400` error because the `refresh_token` param is not set.

### Additional info

Google will only send a `refresh_token` if `access_type=offline`.
Specifically if the goal is to get a new access token when in an online environment, the following should be used: https://developers.google.com/identity/protocols/OAuth2WebServer#request-parameter-prompt

The application should send the user to Google and request a new access token.

### Improvement but not a fix
The implementation of `refreshAccessToken` could check if the `refresh_token` is set before trying to refresh an access token. The standard dictates the `refresh_token` is required so attempting a refresh without it will always fail.

**Comment by klimov-paul** [comment]
You can use [BaseOAuth::$autoRefreshAccessToken](https://github.com/yiisoft/yii2-authclient/blob/master/BaseOAuth.php#L49-L53) to disable automatic access token refreshment.

If you wish to use `access_type=offline`, you should add setup it explicitly to `Google::$authUrl` in client config:

```php
'components' => [
    'authClientCollection' => [
        'class' => 'yii\authclient\Collection',
        'clients' => [
            'google' => [
                'class' => 'yii\authclient\clients\Google',
                'authUrl' => 'https://accounts.google.com/o/oauth2/auth?access_type=offline',
                // ...
            ],
        ],
    ]
    ...
]
```

Unfortunaly neither `$autoRefreshAccessToken` nor `$authUrl` default value can not be changed as it will cause a BC break.

**Comment by klimov-paul** [comment]
> Specifically if the goal is to get a new access token when in an online environment, the following should be used: https://developers.google.com/identity/protocols/OAuth2WebServer#request-parameter-prompt

I am unsure what do you mean as this link does not follow attached anchor, simply opening a docs section at the top and I am unable to find any 'request parameter prompt' amoung the listed topics.

> The implementation of refreshAccessToken could check if the refresh_token is set before trying to refresh an access token. The standard dictates the refresh_token is required so attempting a refresh without it will always fail.

As I said you can disable automatic token refreshment. Cheking for the `refresh_token` param before sending a request **is** possible, but make a little sense: silent skip of `refreshAccessToken()` is not acceptable - the exception should be thrown instead. The only improvent, which can be made is throw `InvalidParamException` right away instead the one, which occurs as the request result - but it makes a little sense.

**Comment by SamMousa** [comment]
Still that improvement at least makes sense. Should I create a PR that throws the `InvalidParamException` when the refresh token is missing?

**Comment by klimov-paul** [comment]
No

**Comment by davidhagen** [comment]
When access_token expires it  should automatically get new access token using initially supplied refresh token if offline request is made. I think this will make this extension completed. At least  It should have an example of get a new refresh token using saved refresh_token
