### ISSUE TITLE
[facebook] BaseOAuth::refreshAccessToken doesn't work.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2-authclient#163]
### What steps will reproduce the problem?
Set up login with Facebook. Get a token.

### What's expected?
When the token expires (which is in 60 days) I expect `refreshAccessToken` to work.

### What do you get instead?
Facebook doesn't use `refresh_token` so there is no way to get a new access token without redirecting the user back to Facebook.
Facebook does allow you to renew the token while still valid but doesn't use a `refresh_token`. Instead it uses exchange: https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension#refreshtokens

**Comment by klimov-paul** [comment]
You can use [BaseOAuth::$autoRefreshAccessToken](https://github.com/yiisoft/yii2-authclient/blob/master/BaseOAuth.php#L49-L53) to disable automatic access token refreshment.

As for Facebook `exchange token` feature - it can be added as an option.
Note, that it will bring benefit only for the applications with short lived tokens.

**Comment by klimov-paul** [comment]
PR opened at #164
