### ISSUE TITLE
code been used errro

### ISSUE THREAD

**Issue by xklake** [yiisoft/yii2-authclient#165]
### What steps will reproduce the problem?
in OAuth2.php function refreshAccessToken(), there should be a bug, i got this error 
a:2:{s:7:"errcode";i:40163;s:6:"errmsg";s:49:"code been used, hints: [ req_id: GL9B5a0685th52 ]";}}') on log file, after dig a bit i found based on document from wechat official website, i am afraid auth code can be used only once within 5 seconds, but this was not handled in refreshAccessToken() function, it still use old code to get access code return an error. 

https://open.weixin.qq.com/connect/oauth2/authorize?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&state=STATE#wechat_redirect

in my opinion, it need authorize before call createToken() in this function. 

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by klimov-paul** [comment]
Authorization code has nothing to do with access token refreshment - it is used only during fetching access token at `fetchAccessToken()`.
Error response like `code been used` should appear only on attempt to exchange same authorization code second time.
Obviously there is some logic error in your application.
