### ISSUE TITLE
GoogleHybrid - origin parameter is required!

### ISSUE THREAD

**Issue by indicalabs** [yiisoft/yii2-authclient#169]
### What steps will reproduce the problem?
Try to login with GoogleHybrid

### What's expected?
Google sign in page to be displayed

### What do you get instead?
```
400. That’s an error.
Error: invalid_request
origin parameter is required!
Learn more
Request Details
    client_id=xxxxx-xxxxx.apps.googleusercontent.com
    response_type=code
    redirect_uri=postmessage
    xoauth_displayname=Matchlink India
    scope=profile email
That’s all we know.

```
### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13-dev
| PHP version      | PHP 7.1.6
| Operating system | Alpine 3.6.0

**Comment by klimov-paul** [comment]
Unable to reproduce.

Note: `GoogleHybrid` relies on related JavaScript code for authentication, do not attempt to invoke `buildAuthUrl()` unless you absolutely sure what you are doing.

**Comment by indicalabs** [comment]
If I use `yii\authclient\clients\Google`, there are no issues. I just changed to the below, which is not working.
```
'class' => 'yii\authclient\clients\GoogleHybrid',
'clientId' => 'xxxx-xxxx.apps.googleusercontent.com',
'clientSecret' => 'xxxx',
'viewOptions' => [
'widget' => [
'class' => 'yii\authclient\widgets\GooglePlusButton',
'buttonHtmlOptions' => [
'data-approvalprompt' => 'force'
],
],
],
```

There are no customizations like invoking `buildAuthUrl().`

**Comment by indicalabs** [comment]
@klimov-paul you are right,
Using $authAuthChoice->clientLink solved the problem
