### ISSUE TITLE
Quick start documentation.

### ISSUE THREAD

**Issue by indicalabs** [yiisoft/yii2-authclient#171]
### What do you get instead?

I think we need correct the documentation at [Quick Start](https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/quick-start.md)

I can't understand what is `if ($auth) `and `$auth->user;` in the below section under `class AuthHandler` 
```
if ($auth) { // login
                /* @var User $user */
                $user = $auth->user;

```

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |
| Yii Auth Client version |
| Yii HTTP Client version |
| PHP version             |
| Operating system        |

**Comment by indicalabs** [comment]
The problem was that the MongoDB won't accept a table with name "auth" 

I changed it too `Auths` then it started working,

but what does it mean  `User with the same email as in Twitter account already exists but isn't linked to it. Login using email first to link it. `

I logged in with Google account first and then the Twitter account which uses the same email.

**Comment by samdark** [comment]
Means it's not safe to log you in via another service when it's not confirmed that you're the same person who already owns an account at our service.
