### ISSUE TITLE
Persistent store

### ISSUE THREAD

**Issue by cbepxpa3ym** [yiisoft/yii2-authclient#177]
Extension uses session to store auth data, and this is right. But session should be just a temporary store (for performance). And there should be a persistent store also to save auth token data after app has been authenticated. So, token data should be saved into db after user authenticated an app, and then passed to session store. Currently token data is lost when session is timed out (or user logs out), and token need to be requested again after next login if website need to make api calls. But it could be fetched from db instead. Why not?

**Comment by klimov-paul** [comment]
This is the part of program flow you should implement in your project on your own if you need it.

**Comment by cbepxpa3ym** [comment]
But the "save" and "load" process from db should be implemented into the setAccessToken and getAccessToken methods of BaseOAuth class. How to do this?

**Comment by cbepxpa3ym** [comment]
Also, the "load" from db should be done before the restoreAccessToken call in getAccessToken method.

**Comment by cbepxpa3ym** [comment]
Can this issue be opened again? I dont think this is the question. This is the enhancement. The event logic should be added to these methods.
