### ISSUE TITLE
Twitter "App-only authentication"

### ISSUE THREAD

**Issue by cbepxpa3ym** [yiisoft/yii2-authclient#178]
https://api.twitter.com/oauth2/token

This feature is not available. Should be the authenticateClient method added to client?

**Comment by klimov-paul** [comment]
I suppose issure refers to this feature:
https://dev.twitter.com/oauth/application-only

**Comment by cbepxpa3ym** [comment]
Yes, that would be great.

**Comment by klimov-paul** [comment]
There is no way I can integrate a single OAuth 2 feature into OAuth 1 client.
The only thing I can do is creation of `TwitterOAuth2` seprated client, which can be used for this feature.
But since Twitter does not provide full support for OAuth 2 such client will be unable to function with user-behalf workflow.

**Comment by cbepxpa3ym** [comment]
Then it would be great to get a separate client, related to the app only functionality. We already have a choice how to use facebook client - use it with user or app workflow. With the Twitter situation we may use a separate classes Twitter or TwitterApp (some combination of OAuth1 and OAuth2 functionality).

**Comment by cbepxpa3ym** [comment]
Currently I made a temporary helper.
[TwitterApi.php.txt](https://github.com/yiisoft/yii2-authclient/files/1248654/TwitterApi.php.txt)

**Comment by klimov-paul** [comment]
Resolved by commit f710531cc241e9176dcaffb8c1d4b37f81f37bd9

**Comment by cbepxpa3ym** [comment]
So, with you code it do this:

GET https://api.twitter.com/1.1/statuses/show.json?id=<if>&access_token=<token>

But should be:

GET https://api.twitter.com/1.1/statuses/show.json?id=<id>
Authorization: Bearer <token>

**Comment by klimov-paul** [comment]
ef7b66a648006b19071b519191f8375a35c929c9
