### ISSUE TITLE
OpenID validation bug

### ISSUE THREAD

**Issue by MattRh** [yiisoft/yii2-authclient#182]
### What steps will reproduce the problem?
I have Steam OpeniID login on my site (implemented by created separate class extending OpenID and redefining `$authUrl = 'http://steamcommunity.com/openid/'`). I also pass returnUrl into it, like that:
```
$return_url = [
    '/auth/end',
    'referrer_url' => Yii::$app->request->referrer
];
$openid = new SteamAuthClient;
$openid->setReturnUrl(Url::to($return_url, true));
```
Recently I had to preciesly specify baseUrl in my urlManager. After that I saw, that $openid->validate() started to always return false. This issue disappeared, if I removed baseUrl.
### What's expected?
Successfull openid validation
### What do you get instead?
validate() returned false

### Additional info
I have found out that if I comment
```
} elseif ($expectedValue != $actualUrlInfo[$name]) {
      //return false;
}
```
this return in OpenID->compareUrl() then everything works fine

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.12
| Yii Auth Client version | 2.1.3
| Yii HTTP Client version | 2.0.4
| PHP version             | 7.0.18
| Operating system        | ubuntu 16.04.1

**Comment by klimov-paul** [comment]
You should use absolute URL including protocol and hostname for `OpenId::$returnUrl`.

**Comment by MattRh** [comment]
But `Url::to($path, true)` generates absolute URL including protocol and hostname

**Comment by klimov-paul** [comment]
Can you dump both `$expectedUrl` and `$actualUrl` to see, which part is different?

**Comment by MattRh** [comment]
`var_dump($expectedUrl, $actualUrl);`
gives
```
string(66) "http://new-jc.xyz/auth/end?referrer_url=http%3A%2F%2Fnew-jc.xyz%2F"
string(83) "http://new-jc.xyzhttp://new-jc.xyz/auth/end?referrer_url=http%3A%2F%2Fnew-jc.xyz%2F"
```

**Comment by klimov-paul** [comment]
There is nothing I can do then: it is obvious you have some mistake while setup `OpenId::$returnUrl` as it have invalid value - `http://new-jc.xyzhttp://new-jc.xyz/auth/end?referrer_url=http%3A%2F%2Fnew-jc.xyz%2F` at the comparison.

**Comment by MattRh** [comment]
No, because on the end on auth it redirects on
```
http://new-jc.xyz/auth/end?referrer_url=http://new-jc.xyz/&openid.ns=http://specs.openid.net/auth/2.0&openid.mode=id_res&openid.op_endpoint=https://steamcommunity.com/openid/login&openid.claimed_id=http://steamcommunity.com/openid/id/76561198057723989&openid.identity=http://steamcommunity.com/openid/id/76561198057723989&openid.return_to=http://new-jc.xyz/auth/end?referrer_url=http%3A%2F%2Fnew-jc.xyz%2F&openid.response_nonce=2017-09-07T15:06:25ZA77KgOC/pg1FFgbolLJ0FGlQxvs=&openid.assoc_handle=1234567890&openid.signed=signed,op_endpoint,claimed_id,identity,return_to,response_nonce,assoc_handle&openid.sig=gZUGTzmuFvq7bpiyOQ7HDwVHy38=
```
Where we can find `openid.return_to=http://new-jc.xyz/auth/end?referrer_url=http%3A%2F%2Fnew-jc.xyz%2F`

**Comment by MattRh** [comment]
And moreover. Probably I found, where is trouble. If we comment `return /*$this->getTrustRoot() . */$url;` in   OpenID->defaultReturnUrl(). Then everything works fine and `var_dump($expectedUrl, $actualUrl);` prints
```
string(66) "http://new-jc.xyz/auth/end?referrer_url=http%3A%2F%2Fnew-jc.xyz%2F"
string(66) "http://new-jc.xyz/auth/end?referrer_url=http%3A%2F%2Fnew-jc.xyz%2F"
```
As it has to

**Comment by klimov-paul** [comment]
> And moreover. Probably I found, where is the trouble. If we comment return /*$this->getTrustRoot() . */$url; in OpenID->defaultReturnUrl().

Method `defaultReturnUrl()` is invoked **only** in case you have NOT specified `returnUrl` on your own, but you clain you did so [here](https://github.com/yiisoft/yii2-authclient/issues/182#issue-255851714).

**Comment by MattRh** [comment]
Idk, but it was called from here `if (!$this->compareUrl($this->data['openid_return_to'], $this->returnUrl)) {` in `OpenID->validate()`. Can you please check this again?

**Comment by MattRh** [comment]
Can you explain, if I type `(new OpenID)->validate()` when does it set `$this->returnUrl`? Because now it seems like it doesn't at all and then to get `returnUrl` it calls `defaultReturnUrl()`
