### ISSUE TITLE
Issues in login with Facebook in yii2-authclient on production

### ISSUE THREAD

**Issue by SOHELAHMED7** [yiisoft/yii2-authclient#183]
### What steps will reproduce the problem?
Just clicking on the facebook icon generates this error (see below image) on production server

### What's expected?
Login with facebook should work fine

### What do you get instead?
Getting this error
![screenshot-full-error](https://user-images.githubusercontent.com/6770119/30367823-0521f2fa-988d-11e7-83e9-2a5cfe7c4e09.png)

### Additional info
In this file 
`yiisoft/yii2-httpclient/StreamTransport.php`
$context of line 60
`$context = stream_context_create($contextOptions);`
print_r($context) yields:

On local system:
Resource id #3

On production
Resource id #124

Login with google and twitter is working fine (both on local and production).
Settings at https://developers.facebook.com/ are :

Client Oauth YES

Web Oauth Login YES

Rest all NO

I have set app id and app secret in config file and also made necessary in SiteController.php for oAuthSuccess callback as mentioned in doc.

I am using below widget to generate icons html code
```
<?= \yii\authclient\widgets\AuthChoice::widget([
        'baseAuthUrl' => ['site/auth'],
]) ?>

```
I am not using [this auth table ](https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/installation.md#storing-authorization-data) but only using **user** table for storing user info.

I have also posted question on [stackoverflow](https://stackoverflow.com/questions/46182368/issues-in-login-with-facebook-in-yii2-authclient-on-production) but got no solution.

I think this belongs to question category not issue, I request to look at this error that it is generating due to extension or from facebook side or something else.

I have done lot research on internet regarding this issue but unable to find solution.

**Production server details:**

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.12
| Yii Auth Client version | 2.1.3
| Yii HTTP Client version | 2.0.4
| PHP version             | 5.5
| Operating system        | Linux  3.2.55-grsec #1 SMP 2014 x86_64
It is on shared hosting

**Local computer info:**

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.12
| Yii Auth Client version | 2.1.3
| Yii HTTP Client version | 2.0.4
 PHP version             | 7.1
| Operating system        | Ubuntu 16.04

**Comment by samdark** [comment]
Check that you've created an app at https://developers.facebook.com and that keys from the app are in configs at your server.

**Comment by SOHELAHMED7** [comment]
Thanks for your  suggestion. Yes, I have made sure keys are same on local and production. And I already have made an app on  https://developers.facebook.com. On local machine all of google, twitter and facebook login are working fine. On production only facebook login is not working and rest all are working fine.

**Comment by samdark** [comment]
You can't use same keys on localhost and in production.

**Comment by SOHELAHMED7** [comment]
I am pretty sure that in case of Google, Facebook and Twitter, I cannot have separate api keys and api secrets for local and production. Google and Twitter login are working fine on local and production with same api keys and api secrets.

**Comment by samdark** [comment]
You can. Make two separate apps with separate URLs.

**Comment by SOHELAHMED7** [comment]
I am unable to understand your point of view in this case.
What is the purpose of making two app at  https://developers.facebook.com - one with local redirect url and another with production redirect url.

However one can make one single app and give two redirect url on  https://developers.facebook.com

**Comment by samdark** [comment]
No.

**Comment by SOHELAHMED7** [comment]
Later I made contact with hosting service provider and they are blocking calls to facebook urls, got the reason, thanks.
