### ISSUE TITLE
Is yii2-authclient support Google ID Token Authentication

### ISSUE THREAD

**Issue by yoyhosoft** [yiisoft/yii2-authclient#188]
### What steps will reproduce the problem?
Here is information:
https://developers.google.com/api-client-library/php/guide/aaa_idtoken
https://developers.google.com/identity/one-tap/web/idtoken-auth

### What's expected?
Support Google ID Token Authentication

### What do you get instead?
- NULL

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | ~2.0.6
| Yii Auth Client version | ~2.1.0
| Yii HTTP Client version | ?
| PHP version             | 5.6.3
| Operating system        | Mac

**Comment by klimov-paul** [comment]
Already solved by #157
