### ISSUE TITLE
Yii 2 - authclient doesn't login with facebook correctly

### ISSUE THREAD

**Issue by Qusai-Azzam** [yiisoft/yii2-authclient#189]
### What steps will reproduce the problem?
i am trying to login with facebook using yii2 
yii\authclient\clients\Facebook , i set the clientId , clienSecret Correctly 
but after success facebook login i got this problem and couldn't get the attributes

HTTP Client Exception – yii\httpclient\Exception

fopen(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0
↵
Caused by: yii\base\ErrorException

### What's expected?
closing the dialog correctly and get the client attributes correctly
### What do you get instead?
HTTP Client Exception – yii\httpclient\Exception

fopen(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0
↵
Caused by: yii\base\ErrorException

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |  2.0.12
| Yii Auth Client version | ~2.1.0
| Yii HTTP Client version |  
| PHP version             | 7.0
| Operating system        |  CentOS
![http](https://user-images.githubusercontent.com/33382409/32914315-cb1b7bc6-cb1d-11e7-9b31-be5e82911405.png)

**Comment by Qusai-Azzam** [comment]
some times the response come like this :
: Bad Request (#400)
Invalid auth state parameter.
The above error occurred while the Web server was processing your request.

**Comment by samdark** [comment]
The reason for it is clearly stated in the error message.

**Comment by Qusai-Azzam** [comment]
thank you for your response i think i resolve the above one, yet another problem appeared
the new problem is : after i logged in to facebook from the app 
it doesn't give me back the parameters and this is the message :
![problem](https://user-images.githubusercontent.com/33382409/32947131-146bfc80-cba3-11e7-9ad5-3befd81c9e48.png)
