### ISSUE TITLE
Default format if not send

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2-authclient#191]
### What steps will reproduce the problem?

/vendor/yiisoft/yii2-httpclient/Client.php
set format null

### What's expected?
      throw new InvalidParamException("Unrecognized format ''");

### What do you get instead?

Set default format json
### Additional info

    public function getParser($format)
    {
        $result = null;
        if (empty($format)) {
            $format = 'json';
        }
        $result = parent::getParser($format);

        return $result;
    }

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.13
| Yii Auth Client version | 2
| Yii HTTP Client version | 2
| PHP version             | 7.1
| Operating system        | ubuntu x64

**Comment by klimov-paul** [comment]
This is expected behavior as message format detected automatically in case it is not set explicitly.
