### ISSUE TITLE
Google not return email

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2-authclient#193]
### What steps will reproduce the problem?
use google client
### What's expected?
email not return
### What do you get instead?
email return

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |2.0.13
| Yii Auth Client version |2
| Yii HTTP Client version |2
| PHP version             |7.1
| Operating system        |ubuntu x64

**Comment by klimov-paul** [comment]
This is expected since Google stores multiple email addresses per user.
You should iterate over `emails` to see them.
