### ISSUE TITLE
Do you have plan to build authclient for "instagram"?

### ISSUE THREAD

**Issue by phamngocson1988** [yiisoft/yii2-authclient#194]
### What steps will reproduce the problem?
Everything is ok
### What's expected?
I hope you have integration for Instagram API. 
### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |
| Yii Auth Client version |
| Yii HTTP Client version |
| PHP version             |
| Operating system        |

**Comment by Felli** [comment]
@kotchuprik has created one already and it still works pretty well. :smile: 

https://github.com/kotchuprik/yii2-instagram-authclient

**Comment by samdark** [comment]
No, we don't have plans to expand number of clients supported. We can link to existing ones from docs though.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-authclient/commit/250591a3f18ddd4b68c1b3208392080cb0d659ef
