### ISSUE TITLE
AuthAction should not access global $_GET

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2-authclient#195]
### What steps will reproduce the problem?
Use `AuthAction`

### What's expected?
That an official extension obeys best practices:
1. Don't use global variables like `$_GET`.
2. Use parameter injection if possible, fall back to getting information from the application request object.

### What do you get instead?
This code in `AuthAction::run()`:
````
    /**
     * Runs the action.
     */
    public function run()
    {
        if (!empty($_GET[$this->clientIdGetParamName])) {
            $clientId = $_GET[$this->clientIdGetParamName];
            /* @var $collection \yii\authclient\Collection */
            $collection = Yii::$app->get($this->clientCollection);
            if (!$collection->hasClient($clientId)) {
                throw new NotFoundHttpException("Unknown auth client '{$clientId}'");
            }
            $client = $collection->getClient($clientId);

            return $this->auth($client);
        }

        throw new NotFoundHttpException();
    }
````

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | N/A
| Yii Auth Client version | master
| Yii HTTP Client version | N/A
| PHP version             | N/A
| Operating system        | N/A

**Comment by klimov-paul** [comment]
Resolved by commit 538af79b7244f6cce51d08d0699f4c9f12747178
