### ISSUE TITLE
Drop OpenID support

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2-authclient#197]
OpenID protocol support will be dropped at version 2.2.0.
This protocol is practically dead at the present state. There is no well known OpenID providers to test possible implementation against.

**Comment by klimov-paul** [comment]
Resolved by commit f4e239b310874da77280e2888843c3801c09a749

**Comment by MattRh** [comment]
Actually there is pretty well known OpenID provider - https://steamcommunity.com/dev
