### ISSUE TITLE
Drop Support for `VKontakte` and `Yandex` clients

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2-authclient#198]
Support of the following clients will be dropped at 2.2.0 version:

- VKontakte
- Yandex

This is necessary for simplification of the core codebase and introduction of more clear policy around country/region local auth provider clients.

Also, since Ukrainian Present's decree #133/2017 IP addresses of 'VKontakte' and 'Yandex' are banned at the territory of my country. Thus, there is no convenient way for me test the possible implementation.

Community should consider of introduction 3rd party clients for 'VKontakte' and 'Yandex' to be used after 2.2.0 release.

**Comment by samdark** [comment]
I can probably host these...

**Comment by klimov-paul** [comment]
Sorry, but I can not take your word for this.
There is too much work to do for Yii 2.1 release. I would ask you to concentrate on issues from main repo, `yii2-debug` and `yii2-gii` instead.
Especially on DI integration and JavaScript rewriting. I will be unable to solve these on my own. Since no other team member is going to be available any time soon, you are the only hope of solving them.
Do you split your scatter your effots over insignificant matters.

If you are willing to create a missing Auth clients afterwards - you should do it under different package.

**Comment by samdark** [comment]
OK. Makes sense.

**Comment by Shketkol** [comment]
I some fix vk auth and I've done pull request

**Comment by samdark** [comment]
There are enough interested users and it seems I have projects to verify against. Decided not to drop support. I'll maintain these.
