### ISSUE TITLE
LinkedIn connections request returns access denied

### ISSUE THREAD

**Issue by mteichtahl** [yiisoft/yii2-authclient#20]
I am using authClient to access linkedIn.

The scope being passed in 'scope' => 'r_fullprofile r_emailaddress r_contactinfo r_network'

This seems to request the right scope in the OAuth request.

however, when later issuing a $this->client->api('people/~/connections', 'GET');

I receive a 

Request failed with code: 403, message: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<error>
<status>403</status>
<timestamp>1430882052185</timestamp>
<request-id>D7N58EN2FU</request-id>
<error-code>0</error-code>
<message>Access to connections denied</message>
</error>

Error.

i cannot determine if this is a linkedIn issue or a possible problem with authClient.

Any guidance would be appreciated

**Comment by klimov-paul** [comment]
Most probably you have not setup a proprer permisions for your application at LinkedIn.

**Comment by mteichtahl** [comment]
This is not the case. r_network is enabled. Have tested against other libraries where this works though I'd prefer to not include a separate library just for LinkedIn. 

Is there anything I can provide that may provide some clues ?

**Comment by klimov-paul** [comment]
Unable to reproduce.

Follwoing code, written in success callback
```php
$result = $client->api('people/~/connections', 'GET');
var_dump($result);
```
outputs correct results.

Make sure you have enabled all necessary permissions at application setup and passed all necessary scopes, which user have approved.

**Comment by mteichtahl** [comment]
can you please confirm which scopes you enabled ?



-----------------------------------------------
Marc Teichtahl
marc@teichtahl.com
Ph: +61 434 100 259
http://www.teichtahl.com

**Comment by klimov-paul** [comment]
I have enabled all.

**Comment by zot24** [comment]
@mteichtahl did you make it work? did you enable all the permissions and worked for you? 

Could be this related with the latest change introduced on LinkedIn API? can we still have access to the `~connections` endpoint after 12 May? sadly is not working for me :tired_face: 

https://developer.linkedin.com/support/developer-program-transition

**Comment by mteichtahl** [comment]
I was unable to make this work.

Im hoping for some direction from the author

-- 
Marc Teichtahl
Sent with Airmail

**Comment by zot24** [comment]
Thanks @mteichtahl! 

Are you aware of LinkedIn API changes isn't it? Have you checked the link I share above? 

I think that's why I can't get the users `connections` because `people/~/connections` endpoint is not for general use anymore.

**Comment by vipullakhtariya** [comment]
@zot24 : To get user connections in linkedin api you need to [apply ](https://developer.linkedin.com/partner-programs/apply)for linkedin partner program.

**Comment by mteichtahl** [comment]
This is now correct. It was not always this way
