### ISSUE TITLE
Return OpenID support

### ISSUE THREAD

**Issue by malsatin** [yiisoft/yii2-authclient#201]
Please, return OpenID support. Still there are service that has only this type of authentication - Steam

**Comment by samdark** [comment]
Yes, Steam is, indeed, a big player. @klimov-paul what do you think about having it back?

**Comment by klimov-paul** [comment]
Can you provide the link to the docs, which describes Steam OpenID: endpoint URL and so on?

**Comment by MattRh** [comment]
https://steamcommunity.com/dev
I think you are interested in `Steam OpenID Provider` section. Quick information:
```
Use http://steamcommunity.com/openid as the provider.
The returned Claimed ID will contain the user's 64-bit SteamID. The Claimed ID format is: http://steamcommunity.com/openid/id/<steamid>
```

And anticipating questions: unfortunatelly then have only OpenID for public usage. They use OAuth only for internal services, so we can't use it
