### ISSUE TITLE
Vk update api and requiere v param

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2-authclient#202]
### What's expected?
    /**
     * @inheritdoc
     * Добавлена версия
     *
     * @link https://vk.com/dev/version_update
     */
    protected function initUserAttributes()
    {
        $response = $this->api('users.get.json', 'GET', [
            'fields' => implode(',', $this->attributeNames),
            'v'      => 5,
        ]);
        $attributes = array_shift($response['response']);

        $accessToken = $this->getAccessToken();
        if (is_object($accessToken)) {
            $accessTokenParams = $accessToken->getParams();
            unset($accessTokenParams['access_token']);
            unset($accessTokenParams['expires_in']);
            $attributes = array_merge($accessTokenParams, $attributes);
        }

        return $attributes;
    }
### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |2.0.13
| Yii Auth Client version |2
| Yii HTTP Client version |
| PHP version             |7
| Operating system        |

**Comment by klimov-paul** [comment]
Already resolved by #179
