### ISSUE TITLE
VK API VERSION

### ISSUE THREAD

**Issue by asger777** [yiisoft/yii2-authclient#207]
as API changed into VK, you should add version of api. i have changed it on my code, please change it on repo too :) have a good day

![image](https://user-images.githubusercontent.com/23039633/37707225-d2940a8e-2d1b-11e8-9347-3d65c6f6602c.png)

**Comment by samdark** [comment]
What do you mean? Is it mandatory requirement now?

**Comment by asger777** [comment]
yes, for now its required.

![image](https://user-images.githubusercontent.com/23039633/37709538-ee860eb0-2d23-11e8-8e1a-fef69b866d5f.png)

**Comment by isudakoff** [comment]
Already resolved by #179 by myself ???

**Comment by samdark** [comment]
Yes :)
