### ISSUE TITLE
unable to use access_token in further request

### ISSUE THREAD

**Issue by AlineWork** [yiisoft/yii2-authclient#208]
### What steps will reproduce the problem?
I've created a client named 'o365' to sign in with Microsoft graph. According to the quick start, signup and login works well. 
 I tried to use the access_token to do other things, I used the following code:
 ```
$o365=Yii::$app->session->get('yii\authclient\clients\O365_o365_token');
        $client=new O365();
        $client->accessToken=$o365;
        $calendar=$client->api("me/events", 'GET');
        .......
```
 After 3600 seconds, the token expired, user have to login again so as to do further things.
I think there might be some mistaken while using auth client. 

### What's expected?
An example to use the access token for further request. 

### What do you get instead?
No guide in documents

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |Latest
| Yii Auth Client version |Latest
| Yii HTTP Client version |Latest
| PHP version             |5.6
| Operating system        |OS X

**Comment by samdark** [comment]
I guess you need to refresh token somehow. I'm not familiar with o365.

**Comment by AlineWork** [comment]
Yes, I do need to refresh it. Finally I find out how to make it work yesterday. The following function in BaseOAuth caused the failure.  By escape the if condition, it works. 
 ```
  public function getAccessToken() {
        if(!is_object($this->_accessToken)) {
            $this->_accessToken=$this->restoreAccessToken();
        }

        return $this->_accessToken;
    }
```

 But I still want to fig out why the origin code of Auth Client didn't work well, did i call class o365 incorrectly cause this.  When I new the class I used following code instead. Is it because the object get form session is an object so it escape the restore part? If is, what is the correct way to new the object?

```
  $o365=Yii::$app->session->get('yii\authclient\clients\O365_o365_token');
        $client=new O365(
            [
                'clientId'=>Yii::$app->params[ 'auth' ][ 'o365' ][ 'clientId' ],
                'clientSecret'=>Yii::$app->params[ 'auth' ][ 'o365' ][ 'clientSecret' ],
                'accessToken'=>$o365
            ]);
```

[Doc of how to get token from Microsoft](https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_user#5-use-the-refresh-token-to-get-a-new-access-token )

**Comment by AlineWork** [comment]
Yes, get it, thank you.
