### ISSUE TITLE
Google Plus required?

### ISSUE THREAD

**Issue by ste-camp** [yiisoft/yii2-authclient#21]
Hello,
I was wondering why is it necessary to enable Google+ APIs for using authclient with google, since it is possible to retrieve user infomation even with no Google+ API sending a GET request to this endpoint:
https://www.googleapis.com/oauth2/v2/userinfo?key={YOUR_API_KEY}

It should require only these scopes:
https://www.googleapis.com/auth/userinfo.email
https://www.googleapis.com/auth/userinfo.profile

This endpoint returns more or less the same info returned by a basic request to Facebook's /me endpoint. Yes, it is actually less than what you get with the current Google+ endpoint, but a lot of it is more than what you need to just implement login

**Comment by klimov-paul** [comment]
Google+ flow is recommened by Google. Also the fact you don't need extra info for user, does not mean there is no one needed it.
And the last: such change will break BC.
