### ISSUE TITLE
RsaSha missing $key in generateSignature()

### ISSUE THREAD

**Issue by cfhodges** [yiisoft/yii2-authclient#211]
### What steps will reproduce the problem?
authenticateUserJwt() fails to decode passphrase protected privatekey.pem file.

### Additional info
There is a bug in yii2-authclient that does not properly use the signatureKey to decrypt the privateCertificateFile.
File: yii2-authclient/src/signature/RsaSha.php
Line: 171
Original Line: $privateKeyId = openssl_pkey_get_private($privateCertificateContent);
Corrected Line: $privateKeyId = openssl_pkey_get_private($privateCertificateContent, $key);
Issue: the $key parameter is missing.

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.15.1
| Yii Auth Client version | 2.1.5
| Yii HTTP Client version | 2.0.6
| PHP version             | 7.0.28
| Operating system        | ubuntu 16.04.1

**Comment by samdark** [comment]
Would you like to make a pull request?

**Comment by cfhodges** [comment]
Sure, pull request #212
