### ISSUE TITLE
Automatically log in

### ISSUE THREAD

**Issue by PanchenkoPetro** [yiisoft/yii2-authclient#216]
### What steps will reproduce the problem?
Good day there was a problem when after the first login when I go to the login page automatically login to Google even if I do not click on the button to login to the application via Google

### What's expected?
I expect it not to log in automatically with google

### What do you get instead?
it automatically log in

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.15
| Yii Auth Client version |2.1.6
| Yii HTTP Client version |2.0.7
| PHP version             |7.1.17
| Operating system        | Linux Mint

**Comment by cebe** [comment]
did you explicitly log out after the first login? Also it is very likely to be a problem in your specific implementation than in this extension, so you should provide more details about how you implemented it.

**Comment by PanchenkoPetro** [comment]
Yes, all right, I logged in then logged out and then when I go to the login page, it automatically logs me in even if I did not click the login button.
I am using the authorization via AuthHandler given in the example, which is listed on this page
https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/quick-start.md

**Comment by samdark** [comment]
That's the way OAuth works.
