### ISSUE TITLE
Binary Data and CONTENT_TYPE_AUTO exception

### ISSUE THREAD

**Issue by friek108** [yiisoft/yii2-authclient#22]
I have been using oAuth2 protocol to access Salesforce API's with no problem for json data. However, I am trying to load binary data (blob files) using their api as mentioned here https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_blob_retrieve.htm

As stated:
>Document body content is returned in binary form. Note that the response content type will not be JSON or XML since the returned data is binary.

When I try to load this data using this class, I get the following exception thrown as the content type cannot be determined: 
``` 
if ($contentType == self::CONTENT_TYPE_AUTO) {
      throw new Exception('Unable to determine response content type automatically.');
}
```
Am I going about this the wrong way? Or should there be a way to specify that content type will be raw / binary / blob but should still be accepted by the OAuth2 class?

**Comment by klimov-paul** [comment]
This extension does not support binary type response. It allows exchanging the strucutred messages, but not raw data.
You should not use `api()` method in this case.
