### ISSUE TITLE
UserInfo request for OpenIdConnect provider doesn't work correctly

### ISSUE THREAD

**Issue by lukos** [yiisoft/yii2-authclient#220]
Use the OpenIdConnect code to create a custom provider (not one of the provided ones like Google). Run a login.

You would expect it to work but the call to UserInfo fails because the access token is passed as a query parameter, even though the OpenId spec [says ](http://openid.net/specs/openid-connect-core-1_0.html#UserInfo) that the provider must support Bearer token header (and some providers only support that).

It is an easy enough fix. I already fixed it to override applyAccessTokenToRequest in OpenIdConnect.php to add it as a header instead of the default param.

Let me know that you're happy with the change and I will send you the PR.

**Comment by samdark** [comment]
Is there any service that fails in this case to test against?

**Comment by lukos** [comment]
Yes, PixelPin (https://login.pixelpin.io) is what I am testing against but it uses [IdentityServer](https://github.com/IdentityServer/IdentityServer3) which only supports bearer token auth so any other site that uses IdentityServer will fail also.

The code that actually handles this in IdentityServer is [here](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Validation/BearerTokenUsageValidator.cs) Line 49. If you use POST you can send the parameter differently but for GET, only the Authorisation header is accepted.
