### ISSUE TITLE
Example Authhandler references non-existent property "github"

### ISSUE THREAD

**Issue by lukos** [yiisoft/yii2-authclient#222]
In the documentation for [QuickStart](https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/quick-start.md), the code references a User property called github which is not mentioned in the database migration code in Installation and is not present in the default User table/model from Yii.

I assume this was accidentally copied from working code where this property was in use but is not needed for this plugin.

If this is correct, I will PR to remove the reference to github including the method updateUserInfo from the quick start Docs.

**Comment by samdark** [comment]
It's to show how to fill extra property you add yourself to User model. That should be clarified.

**Comment by sihar** [comment]
sorry I didn't check this issue before make PR. I already make this PR #299
