### ISSUE TITLE
Change account on sign in

### ISSUE THREAD

**Issue by CristianTan** [yiisoft/yii2-authclient#23]
Is it possible on sign out to end the google session or to give the user the possibility to choose which account he wants?

What I'm trying to do is on every login to give the user the posibility to change the account that he wants to sign in. Can't find any functions to do this. Once the user logged in with an account, that's it. He doesn't have the option to choose another account.

Thanks!

**Comment by klimov-paul** [comment]
OAuth protocol itself does not handle this anyhow. You should browse your application settings and Google documentation for the answer to your question.
If you are using `GoogleHybrid`, you can setup `'data-approvalprompt' => 'force'` in the button options to force user login and confirm scopes:
```php
 'googleHybrid' => [
                    'class' => 'yii\authclient\clients\GoogleHybrid',
                    'clientId' => '...',
                    'clientSecret' => '...',
                    'viewOptions' => [
                        'widget' => [
                            'class' => 'yii\authclient\widgets\GooglePlusButton',
                            'buttonHtmlOptions' => [
                                'data-approvalprompt' => 'force'
                            ],
                        ],
                    ],
                ],
```

**Comment by CristianTan** [comment]
There might be another way:

```php
/**
     * Composes user authorization URL.
     * @param array $params additional auth GET params.
     * @return string authorization URL.
     */
    public function buildAuthUrl(array $params = [])
    {
        $defaultParams = [
            'client_id' => $this->clientId,
            'response_type' => 'code',
            'redirect_uri' => $this->getReturnUrl(),
            'xoauth_displayname' => Yii::$app->name,
            'prompt'=>'select_account'
        ];
        if (!empty($this->scope)) {
            $defaultParams['scope'] = $this->scope;
        }

        return $this->composeUrl($this->authUrl, array_merge($defaultParams, $params));
    }
```

I added ``` 'prompt'=>'select_account' ``` and now is showing the choose your account every time. The ``` data_approvalprompt ``` is asking for permissions every time you want to sign-in.

**Comment by klimov-paul** [comment]
Then there is no problem here, just setup your `authUrl` to be `https://accounts.google.com/o/oauth2/auth?prompt=select_account`

**Comment by CristianTan** [comment]
It actually worked.
So my main.php config file look like this :

```php
		'authClientCollection' => [
			'class' => 'yii\authclient\Collection',
			'clients' => [
				'google' => [
					'class' => 'yii\authclient\clients\GoogleOAuth',
					'clientId' => 'xxx',
					'clientSecret' => 'xxx',
                                        'authUrl'=>'https://accounts.google.com/o/oauth2/auth?prompt=select_account'
				],
			],
		]
```

Thanks a lot!

**Comment by klimov-paul** [comment]
Duplicates https://github.com/yiisoft/yii2/pull/3195
