### ISSUE TITLE
YII2 OAuth Client Instagram - Instagram drops “authclient=instagram” when redirecting

### ISSUE THREAD

**Issue by olissongs** [yiisoft/yii2-authclient#236]
ERROR in AuthAction line 197 crash, becaus no authclient is returned.

i'm using yii2 oauthclinet extension kotchuprik/yii2-instagram-authclient

so its working fien but one thing ist not working

i registered in instagram my app redirurl like that

`myappurl/site/auth?authclient=instagram`

so the redirecturl i expected should be like that:

`myappurl/site/auth?authclient=instagram&code=....`

but it comes:

`myappurl/site/auth?code=...`

using developer tools in browser i recognize:

`https://www.instagram.com/accounts/login/ajax/`

`username=myusernam
password=mypassword
queryParams={"next":"/oauth/authorize?client_id=theclientid&   
response_type=code&redirect_uri=myappurl/site/auth?authclient=instagram&
xoauth_displayname=MyApps&state=statenumbers"}`

so here is it ok the next get request is wrong

`https://www.instagram.com/oauth/authorize?client_id=theclientid&
responsetype=code&redirect_uri=myappurl%2Fsite%2Fauth%3Fauthclient&
xoauth_displayname=MyApps&state=statenumbers

client_id=theclientid
response_type=code
redirect_uri=myappurls%2Fsite%2Fauth%3Fauthclient
xoauth_displayname=MyApp
state=statenumbers
`
here is the =instagram gone

the redirected url from instagram is then:

`myappurl/site/auth?code=codenumbers&state=statenumbers`

so this ist wrong the authclient=instagram is gone lost, i dont know why

any ideas?

### What steps will reproduce the problem?

call `site/auth?authclient=instagram`
Login to instagram
instagram returns with missing autclient paramter (set in Instagram Clients)
error not found exception in 197

### What's expected?

instagram returns  `site/auth?authclient=instagram&code=...&state=...`

### What do you get instead?

instagram returns  site/auth?code=...&state=...

at the Moment if fixed it by extending AuthAction like this, but i think its not a good way:

    `class AuthAction extends \yii\authclient\AuthAction
    {
   
    public function run()
    {
        $clientId = Yii::$app->getRequest()->getQueryParam($this->clientIdGetParamName);
        if (!empty($clientId)) {
            $collection = Yii::$app->get($this->clientCollection);
            if (!$collection->hasClient($clientId)) {
                throw new NotFoundHttpException("Unknown auth client '{$clientId}'");
            }
            $client = $collection->getClient($clientId);

            return $this->auth($client);
        } else {
            $clientId = 'instagram';
            $collection = Yii::$app->get($this->clientCollection);
            if (!$collection->hasClient($clientId)) {
                throw new NotFoundHttpException("Unknown auth client '{$clientId}'");
            }
            $client = $collection->getClient($clientId);
     
            return Yii::$app->response->redirect(['/site/auth','authclient'=>'instagram']);

        }

       // throw new NotFoundHttpException();
    }
    }`

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.15
| Yii Auth Client version | "yiisoft/yii2-authclient": "^2.1",
| Yii HTTP Client version |
| PHP version             | 7.0
| Operating system        | ubuntu 16.04

**Comment by samdark** [comment]
Are you sure it's authclient issue and not instagram client specific one?

**Comment by olissongs** [comment]
i'm a little confused, do you mean with instagram client the original www.instagram.com redirect or the authclient instagram extension?

**Comment by samdark** [comment]
authclient instagram extension

**Comment by olissongs** [comment]
:-)
i started that problem in the repo https://github.com/kotchuprik/yii2-instagram-authclient 
but its not in his responsibility.

so i am new using the Yii2 OAuth Components, Facebook works fine, but i don't know how to catch those errors, so that i can handle it.

It seems that this issue comes when i am logged in as an other user in my device, so i think the instagram extension has to be extended to handle the behavior of instagram.

but i'm not so deep in the yii2 authclient things, that i know which function i have to use to handle this behavior. May adding a feature to switch account or ask for logging off.
So how can get some help for this?

**Comment by samdark** [comment]
Try contacting @kotchuprik. Closing since it's not this extension issue (likely).

**Comment by Felli** [comment]
Well for one Instagram doesn't provide an email scope which will cause frontend issues for those trying to login with it, I had issues with this myself when porting it over to HumHub so it got deprecated pretty quickly, wouldn't recommend using.
