### ISSUE TITLE
yii/db/exception

### ISSUE THREAD

**Issue by karanja1victor** [yiisoft/yii2-authclient#238]
I followed the instructions @ https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/quick-start.md to the letter. But when I click at the g+ link at login I get an error : SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null
The SQL being executed was: INSERT INTO `user` (`username`, `email`, `password_hash`, `auth_key`, `password_reset_token`, `status`, `created_at`, `updated_at`) VALUES (NULL, NULL, '*************************************************', '*************************', '*****************_*****', **, **********, *************). I am using the yii2 advanced template, PHP 7.2, on Ubuntu Linux 18.04.

**Comment by samdark** [comment]
Means in your handler you didn't set username.

**Comment by karanja1victor** [comment]
And how is it that github api works perfectly with the same handler?
