### ISSUE TITLE
Facebook redirect_uri refused with slashes encoded

### ISSUE THREAD

**Issue by infoitservit** [yiisoft/yii2-authclient#239]
### What steps will reproduce the problem?
Go here https://www.winedering.com/user/login, try to login with Facebook. 
### What's expected?
Logging/Subscribing normally
### What do you get instead?
redirect_uri is not accepted.  

### Additional info
The problem is that i can't add the redirect_uri to the facebook app safe url redirect cause the url is encoded ("%2f" in place of "/") and facebook don't accept urls with characters like "%2f".

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.6
| Yii Auth Client version | 
| Yii HTTP Client version | 
| PHP version             | 7.0.12
| Operating system        | Ubuntu 18.04

**Comment by cebe** [comment]
ìf you enable pretty urls you can easily avoid this problem. I don't see any way to fix this in another way, e.g. inside of the extension.

**Comment by infoitservit** [comment]
It's already enabled!

**Comment by cebe** [comment]
How do you end up with characters like  "%2f" in pretty URL in Yii?

**Comment by vityachis** [comment]
I specified the return address in the component parameters and it all worked.
Like this:
```php
'components'          => [
    // Other components
    'authClientCollection' => [
        'class'      => Collection::class,
        'httpClient' => [
            'transport' => CurlTransport::class,
        ],
        'clients'    => [
            'facebook' => [
                'class'        => Facebook::class,
                'returnUrl'    => 'https://example.com/site/auth',
                'clientId'     => '0000000000',
                'clientSecret' => 'xxxxxxxxxx',
            ],
        ],
    ],
],
```
