### ISSUE TITLE
OpenIdConnect::getUserAttributes() fails if the UserInfo endpoint is undefined

### ISSUE THREAD

**Issue by CheckeredFlag** [yiisoft/yii2-authclient#240]
### What steps will reproduce the problem?
If an OpenID Connect provider does not support a UserInfo endpoint, then calling this in `AuthHandler::handle` fails:
> `$attributes = $this->client->getUserAttributes();`

### What's expected?
Should `getUserAttributes()` return the claims from the `id_token` instead?

### What do you get instead?
Throws an exception: `Undefined index: userinfo_endpoint`

### Additional info
Microsoft's Azure AD B2C doesn't support the UserInfo endpoint as mentioned here:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-limitations#restrictions-on-protocols

Furthermore, the OIDC spec states that the UserInfo endpoint is merely recommended to be included in the discovery - not required:
http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

Therefore, the `getUserAttributes()` must not depend on `userinfo_endpoint` being included in the configuration parameters returned by `discoverConfig()`.  Does it make sense for this method to obtain user claims from the `id_token` instead if needed?

Additionally, it seems that `getConfigParam()` ought to return `null` if the given param does not exist instead of throwing an exception.

| Q                       | A
| ----------------------- | ---
| Yii version             |2.0.15.1
| Yii Auth Client version |2.1.5.0
| Yii HTTP Client version |2.0.6.0
| PHP version             |7.1.20-1+ubuntu14.04.1+deb.sury.org+1
| Operating system        |Ubuntu 14.04.5 LTS

**Comment by CheckeredFlag** [comment]
I'd be willing to try my hand at submitting a PR, but I need some direction on what the expected behavior should be.  Any thoughts?

**Comment by samdark** [comment]
Where to get user info for these APIs then?

**Comment by CheckeredFlag** [comment]
An `id_token` is returned as part of the `access_token` in the response with its contents being defined by the scope parameter.  Therefore, the token already has user data via `$client->accessToken->params`.

If a limited `scope` is requested initially (e.g. 'email'), then only the user's email would be included in the claims, so the UserInfo endpoint can be used to request additional information.

Microsoft doesn't currently support a UserInfo endpoint and suggests including `profile` in the `scope` in order to include the user info in the `access_token`.

**Comment by samdark** [comment]
OK. So the answer to

> Should getUserAttributes() return the claims from the id_token instead?

is yes.

**Comment by CheckeredFlag** [comment]
@rhertogh Sorry for the lengthy delay, but yes - I'm able to confirm this resolves the issue for me.  Thanks!
