### ISSUE TITLE
Google oAuth redirect_uri_mismatch

### ISSUE THREAD

**Issue by jakim** [yiisoft/yii2-authclient#241]
Hi,
since yesterday, all of my sites have such an error.
`Request failed with code: 400, message: {"error" : "redirect_uri_mismatch","error_description" : "Bad Request"}`

Interestingly, everything was ok before, the code was not updated. Url given in google `http://localhost:8080/admin/auth/auth?authclient=google`, the error does not occur if I give the same returnUrl in the client configuration.
```php
[
    'class' => \yii\authclient\Collection::class,
    'clients' => [
        'google' => [
            'class' => \yii\authclient\clients\Google::class,
            'clientId' => 'cid', //changed for issue purpose
            'clientSecret' => 'cs', //changed for issue purpose
            'returnUrl' => 'http://localhost:8080/admin/auth/auth?authclient=google',
        ],
    ],
];
```

From what I see, if I do not give returnUrl in the configuration, then url contains the scope, which probably throws an error.

| Q                       | A
| ----------------------- | ---
| Yii version             | latest stable
| Yii Auth Client version |latest stable
| Yii HTTP Client version |latest stable
| PHP version             |7.2
| Operating system        |osx

**Comment by achretien** [comment]
Thx for the fix.

The `defaultReturnUrl` generated when trying to `fetchAccessToken` in the `OAuth2` class look like this:

https://www.exemple.com/auth?authclient=google&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email

At this line : https://github.com/yiisoft/yii2-authclient/blob/7e3b3a362618ff41ac65ff7b10a0d3886959d469/src/OAuth2.php#L191

We should  `unset($params['scope']);`

**Comment by Gectou4** [comment]
If I remove the scope from returned params It's working again  (dam achretien reply at same time :p)

**Comment by motzy** [comment]
We also removed 'scope' from $params to have it work, should be noted that this is in addition to unsetting 'state', not in stead of.

**Comment by ddinchev** [comment]
@samdark can we have a hotfix release for this?

**Comment by newscloud** [comment]
This fixed it for me. Thanks @samdark 
`"require": {
        "yiisoft/yii2": "*",
    "yiisoft/yii2-authclient": "~2.1.7",`

**Comment by github-cuongvm** [comment]
@samdark
Dear boss. Sorry. Bug still appears. Pls hotFix.
with Yii Framework 2 authclient extension: Version 2.2.7 February 12, 2020
Yii 2.0.33 Php 7.2
