### ISSUE TITLE
Wrong the class name in docs

### ISSUE THREAD

**Issue by shoomlix** [yiisoft/yii2-authclient#249]
### What steps will reproduce the problem?
Set up the extension
### What's expected?
Plain work of my site
### What do you get instead?
The error with the message "Class yii\authclient\clients\GoogleOpenId does not exist".

I found that docs about that extension are wroten wrongly. We need to put another class:
yii\authclient\clients\Google instead yii\authclient\clients\GoogleOpenId

But I don't know that will be work or not. Please, inform me.

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.15.1
| Yii Auth Client version | 2.1.7.0
| Yii HTTP Client version | 2.0.6.0
| PHP version             | 7.1
| Operating system        | Windows

**Comment by shoomlix** [comment]
This doc
https://www.yiiframework.com/extension/yiisoft/yii2-authclient/doc/guide/2.0/ru/installation

**Comment by samdark** [comment]
Re-checked. It's not there: https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide-ru/installation.md

**Comment by samdark** [comment]
We'll check why docs update wasn't triggered.
