### ISSUE TITLE
Problems with vk authorization.

### ISSUE THREAD

**Issue by ViRuS-CoBaS** [yiisoft/yii2-authclient#251]
When registering vk application redirect url is specified without get parameters, but in yii-auth client redirect url has parameters authclient=vkontakte, and I get an error redirect_uri is incorrect. How can this be avoided?

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |  2.0.0
| Yii Auth Client version | 2.1.0
| Yii HTTP Client version | 2.0.0
| PHP version             | 7.0
| Operating system        | ubuntu

**Comment by nekit44** [comment]
в настройках приложения Вконтакте сделать пустым поле Доверенный redirect URI

**Comment by machour** [comment]
@ViRuS-CoBaS you can also configure your url manager so that the redirect url is /your/url/authclient/vkontakte

Closing this as @nekit44 provided another workaround.
