### ISSUE TITLE
[Question/Feature] - Google client use G+ API deprecated and "end service" start by 01/2019

### ISSUE THREAD

**Issue by jokamax** [yiisoft/yii2-authclient#258]
### What steps will reproduce the problem?
Just receveived a mail by google that indicates : 
We’re writing to let you know that as part of the sunset of the consumer version of Google+, we will be shutting down our Google+ APIs on March 7, 2019. As part of these changes, Google+ Sign-in has been fully deprecated and will also be shut down on March 7, 2019.
What do I need to know?

On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently fail as early as January 28, 2019.
What do I need to do?

Please update your projects listed below by March 7, 2019 and ensure they are no longer using Google+ APIs. The data below shows which Google+ API methods your projects have recently called.

Note: If you see calls to people.get, these can be the result of using the Google+ Sign-In feature in your application, which is now fully deprecated and is being shut down. Developers should migrate from the Google+ Sign-In feature to the more comprehensive Google Sign-in authentication system.

### What's expected?
I don't know if there is something to change in client and then I come with this issue
If that can help : https://developers.google.com/identity/sign-in/web/quick-migration-guide

Thanks

**Comment by albertborsos** [comment]
Here it is an example which works for me without Google+.

Unfortunately the `userinfo` endpoint returns data in different structure then the `people/me` endpoint of Google+ API.

```php
<?php

namespace app\components\auth\google;

class GoogleLoginClient extends \yii\authclient\clients\Google
{
    public $apiBaseUrl = 'https://www.googleapis.com/oauth2/v1';

    public function init()
    {
        if ($this->scope === null) {
            $this->scope = implode(' ', [
                'https://www.googleapis.com/auth/userinfo.profile',
                'https://www.googleapis.com/auth/userinfo.email',
            ]);
        }
    }

    protected function initUserAttributes()
    {
        return $this->api('userinfo', 'GET');
    }
}
```

**Comment by jokamax** [comment]
It works find (the merged).
Just to adujst data from resultArray (email/name/etc.)

**Comment by albertborsos** [comment]
That's why I did not make a PR. Because my sample is working, but breaks BC.

**Comment by jakim** [comment]
@samdark 
Maybe it's time to release version 2.1.8? A few things are waiting there for a long time. From the perspective of this change, time also plays a key role.

**Comment by samdark** [comment]
Yes. Will be done soon.

**Comment by alexeevdv** [comment]
@albertborsos don't worry about BC. It will stop working anyway because of deprecation :)

**Comment by tomhc** [comment]
We've got several production sites utilitizing the Google auth that relies on Google+, and Google says the API will start failing sporadically the end of January 2019, which is now. If there isn't a firm release date for 2.1.18, that's OK, we just need to know and plan accordingly.

Thank you,

Tom Remmers
www.apana.com
tom.remmers@apana.com

**Comment by samdark** [comment]
https://www.yiiframework.com/news/193/auth-client-extension-2-1-8-released
