### ISSUE TITLE
LinkedIn - cannot post to the API

### ISSUE THREAD

**Issue by andrei-livadariu** [yiisoft/yii2-authclient#26]
The authclient extension provides an `api` method used to send API requests. There is a problem when using this method in order to send POST requests to LinkedIn. According to the [documentation](https://developer.linkedin.com/docs/share-on-linkedin) for sharing content, the proper way to send data is by setting the POST body directly as JSON or XML, not as key-value parameters.

At the moment, this method of sending data is not available within the extension. In the `OAuth2` class, the method `composeRequestCurlOptions` (which internally handles this part of the request flow) treats the parameters as an array and calls `http_build_query` on them. There are ways around this, such as extending the class and overriding the behavior, but they are rather clunky and they make the developer think more than necessary :)

A possible solution would be to expose a parameter in `OAuth2` that controls the way POST data is encoded. Then child classes such as LinkedIn can choose the method they need.

Perhaps this is a bit besides the point of the authclient extension, because it's not strictly authentication-related. Still, this issue does not deal with deep integration between LinkedIn and Yii. Rather, it deals with one of the possible ways to transmit data to an OAuth API. From this point of view, it might make sense to develop a fix.

**Comment by klimov-paul** [comment]
Same as https://github.com/yiisoft/yii2/issues/6961

**Comment by smorocho** [comment]
This is solved with this pull request https://github.com/yiisoft/yii2-authclient/pull/33
