### ISSUE TITLE
Twitter is not working (requestToekn)

### ISSUE THREAD

**Issue by valsha** [yiisoft/yii2-authclient#264]
![Clipboard01](https://user-images.githubusercontent.com/7966513/54389966-042db600-46aa-11e9-9cc3-dcee7c091306.jpg)

### What steps will reproduce the problem?
Twitter always ask - **requestToekn**
My consumerKey and consumerSecret are CORRECT
### What's expected?
Twitter Sign is not working
### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.16.1
| Yii Auth Client version | 2.1.8
| Yii HTTP Client version |
| PHP version             | 7.2.15
| Operating system        | Ubuntu 18.04

**Comment by samdark** [comment]
I've re-checked if authentication works at https://gostash.it/en that uses Yii and authclient. It does. Please provide more details on how to reproduce it.

**Comment by valsha** [comment]
> 
> 
> I've re-checked if authentication works at https://gostash.it/en that uses Yii and authclient. It does. Please provide more details on how to reproduce it.
Thank you, maybe you can check it here - https://dev-alex.gametopx.com Twitter is not working.
What info do you need?

**Comment by samdark** [comment]
Started checking but I don't want to give the app permissions to update my profile and post on my behalf. If you're not using it, please reduce permissions set to `scope = 'email'`.

**Comment by valsha** [comment]
> 
> 
> Started checking but I don't want to give the app permissions to update my profile and post on my behalf. If you're not using it, please reduce permissions set to `scope = 'email'`.

It is done (scope = 'email') please, check it. Thank you for your help.

**Comment by samdark** [comment]
Still requests too much.

**Comment by samdark** [comment]
Anyway, I'll set up a test account...

**Comment by samdark** [comment]
Yup. Reproduced in your case but have no idea what's wrong. Please provide your config for authclients excluding any private keys.

**Comment by valsha** [comment]
> 
> 
> Yup. Reproduced in your case but have no idea what's wrong. Please provide your config for authclients excluding any private keys.

Do I need public here all this info? I think this is private and sensitive data.

**Comment by samdark** [comment]
That's why I emphasized on "excluding any private keys".

**Comment by valsha** [comment]
'authClientCollection' => [
            'class' => 'yii\authclient\Collection',
            'clients' => [
                'vkontakte' => [
                    'class' => 'app\components\VKontakte',
                    'clientId' => ,
                    'clientSecret' => '',
                    'scope' => 'email'
                ],
                'google' => [
                    'class' => 'app\components\Google',
                    'clientId' => '',
                    'clientSecret' => '',
                ],
                'facebook' => [
                    'class' => 'app\components\Facebook',
                    'clientId' => '',
//                  'validateAuthState' => false,
                    'clientSecret' => '',
                ],
                'twitter' => [
                    'class' => 'budyaga\users\components\oauth\Twitter',
                    'consumerKey' => '',
                    'consumerSecret' => '',

**Comment by samdark** [comment]
Seems you're using custom clients instead of [built-in ones](https://github.com/yiisoft/yii2-authclient/tree/master/src/clients). We cannot fix bugs in these. Please report to that code authors instead.
