### ISSUE TITLE
User Login, Authchoice Google +  (G+)

### ISSUE THREAD

**Issue by nurielmeni** [yiisoft/yii2-authclient#265]
### What steps will reproduce the problem?
User Login page
### What's expected?
To see the google logo on Authchoice
### What do you get instead?
The G+ (google +) which is not available anymore

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |2.0.16.1 
| Yii Auth Client version |2.1.7
| Yii HTTP Client version |2.0.7
| PHP version             |7.2.15
| Operating system        |Ubuntu Server

**Comment by samdark** [comment]
Yes because it's discontinued: https://support.google.com/plus/answer/9217723?hl=en&authuser=0

**Comment by nurielmeni** [comment]
Right, so the icon need to be updated to the Google icon to be in accordance to google
![authchoice](https://user-images.githubusercontent.com/662907/54599095-9b945f80-4a42-11e9-912b-e518e8760d25.png)

![new-google-favicon-128](https://user-images.githubusercontent.com/662907/54599117-a3ec9a80-4a42-11e9-8116-2d475b52b930.png)
Add this instead of the g+ one

![authchoice](https://user-images.githubusercontent.com/662907/54599569-91269580-4a43-11e9-80b9-161d0472371c.png)

**Comment by samdark** [comment]
Right. Would you like to make a pull request?
