### ISSUE TITLE
LinkedIn V1 api is deprecated

### ISSUE THREAD

**Issue by mzglinski** [yiisoft/yii2-authclient#267]
### What steps will reproduce the problem?
Authorization request to linkedin.

### What's expected?
Successful authorization.

### What do you get instead?
`Request failed with code: 410, message: 410 1553362185015 YD4Y3EONFJ 0 This resource is no longer available under v1 APIs`

### Additional info

This happens because as of March 1, 2019 version 1 of linkedin ouath api is discontinued.
V2 docs: https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.17
| Yii Auth Client version | 2.1.8
| Yii HTTP Client version | 2.07
| PHP version             | 7.2.16
| Operating system        | php 7.2.16-fpm-stretch docker image

**Comment by jakubsyrek** [comment]
When it will be released?

**Comment by machour** [comment]
@jakubsyrek could you test dev-master? If it works for you, I guess @samdark could cut a release shortly

**Comment by machour** [comment]
Seems like LinkedIn extended v1 lifecycle for two months :)

See disclaimer at https://engineering.linkedin.com/blog/2018/12/developer-program-updates

Re-opening as a reminder that we need to publish a new version of yii2-authclient before May 1st
