### ISSUE TITLE
Why not remove the dependency of curl extension?

### ISSUE THREAD

**Issue by hightman** [yiisoft/yii2-authclient#27]
The PHP built-in function `file_get_contents()`, fully supports all kinds of HTTP requests since 5.0.0.

I strongly hope to cancel the dependence of CURL, I never like to install extra extension, unless there is no choice.

thanks.

**Comment by klimov-paul** [comment]
`file_get_contents()` can only read the response from URL, it can not perform POST request and does not allow setup of custome headers and so on. CURL extension is necessary.

**Comment by samdark** [comment]
@klimov-paul you can do all that with file_get_contents: http://stackoverflow.com/questions/2445276/how-to-post-data-in-php-using-file-get-contents

**Comment by hightman** [comment]
@klimov-paul You really did not knows about the function `file_get_contents()`, look the third parameter, it almost supports all of HTTP request.

**Comment by hightman** [comment]
If you have not plan to implement this feature, I intend to submit the patch, but has not yet begun to write code.

**Comment by samdark** [comment]
A patch would be great.

**Comment by klimov-paul** [comment]
Any enhancement at this matter does not make sense unless there is a final resolution on https://github.com/yiisoft/yii2/issues/2953

Migration from CURL to stream will break a BC as some client functions manipulate CURL options.

**Comment by samdark** [comment]
Well, if CURL stuff is exposed via public API we definitely can't touch it in 2.0.x.

**Comment by hightman** [comment]
Now I open a pull request about #27, But sorry to generate another issue #28.  I think this patch will not break the compatible with cURL.

**Comment by klimov-paul** [comment]
Resolved via #117
