### ISSUE TITLE
validateClaims() in yii\authclientOpenIdConnect is private

### ISSUE THREAD

**Issue by marty-macfly** [yiisoft/yii2-authclient#273]
Thanks for the work done on that very nice extension.

### What steps will reproduce the problem?

I'm wondering if there is any reason for `validateClaims()` method to be `private` ? In my case I need to change the behavior of the `validateClaims()` method and to do that I need to override the `createToken()` method and mostly copy past all the inheritance code to just be able to override the `validateClaims()`.

### What's expected?

`validateClaims()` method can be make `protected` instead ?

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.19
| Yii Auth Client version |  2.2.2
| Yii HTTP Client version | 2.0.11
| PHP version             | 7.2.18
| Operating system        | Debian 9

**Comment by samdark** [comment]
What do you want to change? Is that change specific for your case or is it fixing something?

**Comment by marty-macfly** [comment]
In my case I'm using the OpenIdConnect client `setAccessToken()' method to validate that an OpenId access token is valid. But in my access token the `aud` claim doesn't contain the client Id so the `validateClaims()` method failed, so I change it to use the `azp` claim. I think it's may be related to that https://stackoverflow.com/questions/41231018/openid-connect-standard-authorized-party-azp-contradiction

**Comment by samdark** [comment]
Thanks for info. That is valid to change. Want to speed it up with a pull request?
