### ISSUE TITLE
Vk versions below 5.00 are deprecated

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2-authclient#276]
### What steps will reproduce the problem?
I send request for auth by VK
### What's expected?
Invalid request: versions below 5.00 are deprecated
### What do you get instead?
correct auth

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |2.0.15
| Yii Auth Client version |2.2.3
| Yii HTTP Client version |latest
| PHP version             |7.1.19
| Operating system        |Ubuntu

**Comment by EvgeniyRRU** [comment]
So, if you have some flamed asses (like me), and VK OAuth totally broken at you projects, you can change dependency manual. You can change file `/vendor/yiisoft/yii2-authclient/src/client/VVKontakte.php` line 79 from
```php
public $apiVersion = '3.0';
```
to:
```php
public $apiVersion = '5.0';
```
But this is a dirty hack. And I don't recommend it.

@des1roer, current actual version of `yiisoft/yii2-authclient` (2.2.3) already fixed this issue. So, you should to update your dependencies.

@samdark but vk developers recommend use as last version as possible (see [here](https://vk.com/dev/version_update_2.0)). Therefore, it will be better if [this](https://github.com/yiisoft/yii2-authclient/blob/master/src/clients/VKontakte.php#L79) line will be changed from 
```php
public $apiVersion = '5.0';
```
to
```php
public $apiVersion = '5.95';
```
