### ISSUE TITLE
Ability to set a default clientId of AuthAction via a property

### ISSUE THREAD

**Issue by gtaranti** [yiisoft/yii2-authclient#279]
I'm using the extension to authenticate via Microsoft Azure OAuth2.

In Azure the redirect-url is not permitted to contain queries after the main url.
So I cannot set the redirect-url to` https://<MY_HOST>/site/auth?q=azure`
This throws an exception in run() of AuthAction, because it expects a clientId.

For now I've hardcoded the clientId in the AuthAction run() function and it works very good.
But I propose to introduce a defaultClientId property in the AuthAction class in order to utilise it in the actions() configuration of the SiteController like this :

```php
public function actions()
    {
        return [
…..
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
		   ‘defaultClientId’ => ‘azure’
            ],
        ];
    }
```

Of course the respective check has to be done in the run() function (line 201) : 

```php
$clientId = Yii::$app->getRequest()->getQueryParam($this->clientIdGetParamName) || $this->defaultClientId;
```

**Comment by samdark** [comment]
Sounds OK. Do you want to prepare a pull request for it?

**Comment by gtaranti** [comment]
OK,  I'll try to do it.
See, I haven't done a pull request before!

Thanks.

**Comment by gtaranti** [comment]
So,

I've
- forked the repo
- cloned locally
- created a new branch
- made the changes
- committed
- pushed to my forked repo
- created a pull request

but failed because I'm not authorised !
What now?

**Comment by samdark** [comment]
Push into your own fork. I guess you're trying to push into this repository directly.

**Comment by gtaranti** [comment]
OK, I pushed to my forked repo, and merged the pull request.
Now what?

**Comment by samdark** [comment]
Ideally, unit tests. Not ideally, I'll add tests myself but it will take some extra time...

**Comment by rjma30** [comment]
hi samdark, when do you think this will be available? Thanks!

**Comment by samdark** [comment]
When someone will implement it.
