### ISSUE TITLE
redirect_uri is returnUrl

### ISSUE THREAD

**Issue by sergeizhukov** [yiisoft/yii2-authclient#281]
I Spent much time to find out the reason.
First isn't clear about `returnUrl` we need fill it.
So when we forwarding from the service to web-site the Auth client doesn't know a requested service.

Add please in documentation that we need `returnUrl` with attached `?authclient=github`

```php
 'github' => [
                    'class' => yii\authclient\clients\GitHub::class,
                    'clientId' => getenv('GITHUB_CLIENT_ID'),
                    'clientSecret' => getenv('GITHUB_CLIENT_SECRET'),
                    'returnUrl' => 'http://fdsgn.local/auth/auth?authclient=github',
                ],
```

**Comment by samdark** [comment]
> First isn't clear about returnUrl we need fill it.

It works well without `returnUrl`. For example, https://yiipowered.com/en doesn't have it configured explicitly. You have to set "Authorization callback URL" in the GitHub application settings though. It is described in [GitHub documentation](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#redirect-urls) that is linked from [GitHub client class phpdoc](https://www.yiiframework.com/extension/yiisoft/yii2-authclient/doc/api/2.2/yii-authclient-clients-github).
