### ISSUE TITLE
Hello i have a problen using OpenID Connect and Keycloak as Auth Server

### ISSUE THREAD

**Issue by gvalmana** [yiisoft/yii2-authclient#289]
### What steps will reproduce the problem?
My problem is when the user logged with the auth provider, i always got after login
Request failed with code: 404, message: <html><head><title>Error</title></head><body>404 - Not Found</body></html>
### Additional info
Im using worteks/yii2auth-oidc as OIDC
| Q                       | A
| ----------------------- | ---
| Yii version             |2.0.14
| Yii Auth Client version |2.2
| Yii HTTP Client version |2.0
| PHP version             |7.2.11
| Operating system        |Linux MInt 19.2

**Comment by samdark** [comment]
What's the URL of the page that gives you 404?

**Comment by gvalmana** [comment]
This is the url, im running keycloak on a docker container
`http://172.17.0.1/basic-ajax/web/site/auth?authclient=yii2&state=390bb758e2c051d64c380adf37cdd894fc3d8e1dd932181cb4dcdd271bad11ff&code=24c0188c-8f19-4a1d-be46-e115d2502580.b3748efb-41f0-48f1-88ff-11e3d3c8704b.d3e443be-c05a-492a-88ec-43d94bd33f42`

**Comment by samdark** [comment]
Do you have `actionIndex()`? Does `http://172.17.0.1/basic-ajax/web/site/index` work?

**Comment by gvalmana** [comment]
> http://172.17.0.1/basic-ajax/web/site/index

Yes it works

**Comment by samdark** [comment]
Any idea what HTTP method is used when requesting `http://172.17.0.1/basic-ajax/web/site/auth?authclient=yii2&state=390bb758e2c051d64c380adf37cdd894fc3d8e1dd932181cb4dcdd271bad11ff&code=24c0188c-8f19-4a1d-be46-e115d2502580.b3748efb-41f0-48f1-88ff-11e3d3c8704b.d3e443be-c05a-492a-88ec-43d94bd33f42`?

**Comment by gvalmana** [comment]
Yiie Debug show me this
$_GET = [
    'authclient' => 'yii2',
    'state' => '706d00810025eb90888508041e68e1083c0705d503ea6c7db05c0c222af899b2',
    'session_state' => 'f63a6171-b7df-4bdf-9c7b-d8aade72e433',
    'code' => '23c0083a-ea9a-427e-bb66-9f67447d2250.f63a6171-b7df-4bdf-9c7b-d8aade72e433.b5e59330-6be1-4499-8dfb-25c0051c6886',
];

**Comment by samdark** [comment]
$_SERVER['REQUEST_METHOD']?

**Comment by gvalmana** [comment]
> $_SERVER['REQUEST_ME

> $_SERVER['REQUEST_METHOD']?
sorry where i whould use that?

**Comment by samdark** [comment]
It's in the debug toolbar:

<img width="717" alt="Annotation 2019-11-29 195803" src="https://user-images.githubusercontent.com/47294/69882833-9f22fa80-12e2-11ea-8c2b-cddd61d546f1.png">

**Comment by gvalmana** [comment]
Good morning the method is GET, anyway I already resolved, is that I used a third-party library Worteks/yii2auth-oidc that was suggested here, and change to the OpenIDConnect of the extension itself, thanks for your help, Now I will try to see how I get the user roles that are in the payload of the Bearer Token provided by Keycloak
