### ISSUE TITLE
api wall.post

### ISSUE THREAD

**Issue by doroshuk** [yiisoft/yii2-authclient#29]
Привет. Пытаюсь запостить сообщение на стену залогиненому пользователю.

Настройки приложения
api = Включил
тип приложения = standalone

'authClientCollection' => [
            'class' => 'yii\authclient\Collection',
            'clients' => [              
                'vkontakte' => [
                    'class' => 'yii\authclient\clients\VKontakte',             
                    'clientId' => 'прописал id приложения',
                    'clientSecret' => 'прописал секретный ключ приложения',                 
                    'scope' => 'wall,offline'
                ],               
        ],

public function successCallback($client) {
        $attributes = $client->getUserAttributes();
       //Пользователь логинится нормально. Получаю по нему все данные.

        print_r($client->api('wall.post','GET',['owner_id'=>$attributes['id'],'message'=>'test'])); exit;
        // [error_code] => 15 [error_msg] => Access denied: no access to call this method
    }

Но у меня почему-то ошибка при вызове wall.post.  Access denied: no access to call this method

**Comment by klimov-paul** [comment]
@doroshuk, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
