### ISSUE TITLE
Can not set HTTPS-Protocol

### ISSUE THREAD

**Issue by likont** [yiisoft/yii2-authclient#290]
Facebook requir redirect URL only with HTTPS-protocol(http://ipic.su/img/img7/fs/kiss_9kb.1580221427.png). 
But extension generate just HTTP URL.
Method \yii\authclient\BaseOAuth::defaultReturnUrl use createAbsoluteUrl() for generate redirect URL, but can not change second param and set HTTPS-protocol. As result we has HTTP link which Facebook does not allow: http://ipic.su/img/img7/fs/kiss_10kb.1580221485.png
Json encoded response: http://ipic.su/img/img7/fs/kiss_6kb.1580221550.png

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.32
| Yii Auth Client version | 2.1
| Yii HTTP Client version | Not used. 
| PHP version             | 7.2.2
| Operating system       | CentOS 7

**Comment by samdark** [comment]
`BaseOAuth::defaultReturnUrl()` doesn't specify protocol. It means return URL generated matches protocol used at the website. If your website is served via HTTP it doesn't make sense to set return URL to HTTPS.

**Comment by temposys** [comment]
I have the same problem. My case: i use AWS Certificate manager + Load balancer
so my site uses http protocol and server doesn't know anything about ssl and load balancer makes it to be https for users. 
and in this case code generates http links and facebook login doesn't work.
