### ISSUE TITLE
How to save a token of a user in order to use it later

### ISSUE THREAD

**Issue by skiiiks** [yiisoft/yii2-authclient#295]
Hi:
I'm using this module to let users to connect their social accounts (like Instagram, Twitter, etc. ..), so I ask for permissions to post on behalf them.

When they are logged, they connect their accounts, but, after that, I'd like some cron jobs to get this credentials and use them to publish something in their social networks.

I try to use this:
$client = Yii::$app->authClientCollection->getClient("instagram");

but this is trying to get the instagram client of MY user, not of their user object.

How can I retrieve a client of another user and use it ?

Thank you

**Comment by skiiiks** [comment]
Please, I need this ... authclient is working perfectly for LOGIN into a system, but I need to use it with other purposes, like "google calendar sync" or "posting in a Twitter account" after the login, in the future ... so I need access_token to do the calls.

**Comment by samdark** [comment]
Likely that's not the same token but a server token. But if it's the same one, try getting one from https://github.com/yiisoft/yii2-authclient/blob/master/src/AuthAction.php#L41
