### ISSUE TITLE
Add support for Client Credentials grant type

### ISSUE THREAD

**Issue by RomeroMsk** [yiisoft/yii2-authclient#30]
OAuth2 client now is working only with `authorization_code` grant, but there is another way of obtaining an access token: `client_credentials` grant (you can read [here](https://bshaffer.github.io/oauth2-server-php-docs/grant-types/client-credentials/), for example).
So, to use this grant we need to extend `OAuth2` class to change `fetchAccessToken` method, including it's signature (beacuse authCode is not used in this grant).
Why not add support of this common used grant to extension?

**Comment by thejahweh** [comment]
:+1: 

also `user_credentials`/`password` would be nice.

**Comment by cncap** [comment]
@klimov-paul Jolly Good work man! I have just met the problem, thank you very much for you can put this issue on the agenda

**Comment by klimov-paul** [comment]
Resolved by commit 0bf628c7773113ef8d4a01e134679d1361786baa
