### ISSUE TITLE
Yii2 authclient invalid authstate login with google

### ISSUE THREAD

**Issue by ravithanki15** [yiisoft/yii2-authclient#301]
Hello samdark

I have used yii2 authclient for login with google and facebook.
Its working fine but last fews days i face error like "Invalid auth state" in login with google or facebook.
![222](https://user-images.githubusercontent.com/5066316/83935543-3b6d1300-a7d8-11ea-90fb-ad34586666bf.PNG)

By some reserch and found solution that add validateAuthState' => false, this was worked in facebook but google not working.

'authClientCollection' => [
              'class' => 'yii\authclient\Collection',
              'clients' => [
                  'google' => [
                      'class'        => 'yii\authclient\clients\Google',
					  //'validateAuthState' => false,
                      'clientId'     => '641202039882-fcra4ke8vguuvqvkgosihiqfi3jimmk0.apps.googleusercontent.com',
                      'clientSecret' => 'Wkx5UmpUDJRslX0-5lff1Hev',
					  'returnUrl'=>'http://customer-ttcleaning.bigpos.net/user/auth?authclient=google',
                  ],
                  'facebook' => [
                      'class' => 'yii\authclient\clients\Facebook',
					  'validateAuthState' => false, 
					  'authUrl' => 'https://www.facebook.com/dialog/oauth?display=popup',
                      'clientId' => '606918416800040',
                      'clientSecret' => '4d2f6991a21c91fb7f2dc79399ff20a9',
					  'attributeNames' => ['name', 'email', 'first_name', 'last_name'],
                  ]
                ],
        ],

Please help to resolve this.

Thank you.

**Comment by ravithanki15** [comment]
Can you help me resolve this @samdark ?

**Comment by ravithanki15** [comment]
@samdark can you help me resolve this ?

**Comment by ravithanki15** [comment]
@samdark @machour @cebe @munawer-t Can anyone help ?

**Comment by samdark** [comment]
@ravithanki15 we have to check it in detail. Still had no chance to allocate time and dig it properly.

**Comment by ravithanki15** [comment]
@samdark which details you want ? i will provide you.

**Comment by pigochu** [comment]
The same error .
Facebook development mode (localhost) is ok , but production mode got error.

```
2020-07-03 08:20:08 [10.0.2.5][-][d4ce873e669010647c9c260711bb4422][error][yii\authclient\InvalidResponseException] yii\authclient\InvalidResponseException: Request failed with code: 400, message: {"error":{"message":"\u7121\u6cd5\u8f09\u5165\u7db2\u5740: \u9019\u500b\u7db2\u5740\u7684\u7db2\u57df\u672a\u5305\u542b\u5728\u61c9\u7528\u7a0b\u5f0f\u7684\u7db2\u57df\u4e2d\u3002\u82e5\u8981\u8f09\u5165\u9019\u500b\u7db2\u5740\uff0c\u8acb\u5728\u61c9\u7528\u7a0b\u5f0f\u8a2d\u5b9a\u7684\u300c\u61c9\u7528\u7a0b\u5f0f\u7db2\u57df\u300d\u6b04\u4f4d\u4e2d\u65b0\u589e\u61c9\u7528\u7a0b\u5f0f\u7684\u6240\u6709\u7684\u7db2\u57df\u53ca\u5b50\u7db2\u57df\u3002","type":"OAuthException","code":191,"fbtrace_id":"AzZU7_xi0v_Kf91_2drcrlv"}} in /app/vendor/yiisoft/yii2-authclient/src/BaseOAuth.php:232
Stack trace:
#0 /app/vendor/yiisoft/yii2-authclient/src/OAuth2.php(124): yii\authclient\BaseOAuth->sendRequest(Object(yii\httpclient\Request))
#1 /app/vendor/yiisoft/yii2-authclient/src/clients/Facebook.php(148): yii\authclient\OAuth2->fetchAccessToken('AQAN4tHGU1jCe0r...', Array)
#2 /app/vendor/yiisoft/yii2-authclient/src/AuthAction.php(415): yii\authclient\clients\Facebook->fetchAccessToken('AQAN4tHGU1jCe0r...')
#3 /app/vendor/yiisoft/yii2-authclient/src/AuthAction.php(226): yii\authclient\AuthAction->authOAuth2(Object(yii\authclient\clients\Facebook), Array)
#4 /app/vendor/yiisoft/yii2-authclient/src/AuthAction.php(210): yii\authclient\AuthAction->auth(Object(yii\authclient\clients\Facebook))
```

**Comment by pigochu** [comment]
@samdark 

In my case , My production site use cloudflare flex ssl mode , my server use yii2-docker image , and no ssl config.
I trace the log, authClient send a request to get accessToken , and set redirect_uri=http://mydomain (Its not https) . its not https . so return 400 error.
How to force authClient to use https ???

**Comment by samdark** [comment]
Yes, that's OK and we can't fix that in the code itself. That should be documented.

@ravithanki15 is that your case as well?

**Comment by zzbajie** [comment]
I also encountered a similar problem. Everything happened without any changes. The problem was that it was not possible in Android, but it was indeed possible in ios. It was a strange problem.

**Comment by srakl** [comment]
my google login suddenly stopped working today. both on chrome and firefox, 

i tried `$_SERVER['HTTPS']='on';` in `web/index.php` but no luck.

got a fix for it? @samdark thanks

```
yii\web\HttpException: Invalid auth state parameter. in C:\xampp\htdocs\yii2\vendor\yiisoft\yii2-authclient\src\OAuth2.php:122
Stack trace:
#0 C:\xampp\htdocs\yii2\vendor\yiisoft\yii2-authclient\src\AuthAction.php(417): yii\authclient\OAuth2->fetchAccessToken('4/0AX4XfWg74k__...')
#1 C:\xampp\htdocs\yii2\vendor\yiisoft\yii2-authclient\src\AuthAction.php(227): yii\authclient\AuthAction->authOAuth2(Object(Da\User\AuthClient\Google), Array)
#2 C:\xampp\htdocs\yii2\vendor\yiisoft\yii2-authclient\src\AuthAction.php(210): yii\authclient\AuthAction->auth(Object(Da\User\AuthClient\Google))
#3 [internal function]: yii\authclient\AuthAction->run()
#4 C:\xampp\htdocs\yii2\vendor\yiisoft\yii2\base\Action.php(94): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\yii2\vendor\yiisoft\yii2\base\Controller.php(181): yii\base\Action->runWithParams(Array)
#6 C:\xampp\htdocs\yii2\vendor\yiisoft\yii2\base\Module.php(534): yii\base\Controller->runAction('auth', Array)
#7 C:\xampp\htdocs\yii2\vendor\yiisoft\yii2\web\Application.php(104): yii\base\Module->runAction('user/security/a...', Array)
#8 C:\xampp\htdocs\yii2\vendor\yiisoft\yii2\base\Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#9 C:\xampp\htdocs\yii2\frontend\web\index.php(43): yii\base\Application->run()
#10 {main}
```
