### ISSUE TITLE
beforeApiRequestSend logic improvement suggestion

### ISSUE THREAD

**Issue by marty-macfly** [yiisoft/yii2-authclient#309]
### What steps will reproduce the problem?

When we have `BaseOAuth->autoRefreshAccessToken = true` and the access token is expired the `beforeApiRequestSend` method will trigger an  'Invalid access token.'

### What's expected?

I think if we have `autoRefreshAccessToken = true` and the access token is not valid anymore in fact we should not raised an exception but refresh the access token to have a valid one and be able to do the query, if refresh token is expired exception will be raised.

something like that should do the work:

```php
    public function beforeApiRequestSend($event)
    {
        $accessToken = $this->getAccessToken();
        if (!is_object($accessToken) || !$accessToken->getIsValid()) {
           if (!$this->autoRefreshAccessToken && is_object($accessToken)) {
             throw new Exception('Invalid access token.');
           }
          $this->refreshAccessToken($accessToken);
        }

        $this->applyAccessTokenToRequest($event->request, $accessToken);
    }
```

Does it seems a relevant change to you ?

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii Auth Client version | 2.2.7

**Comment by samdark** [comment]
Yes, looks relevant. Do you want to implement it?

**Comment by marty-macfly** [comment]
Yes, I'll submit a PR
