### ISSUE TITLE
Make using of refreshAccessToken optional

### ISSUE THREAD

**Issue by RomeroMsk** [yiisoft/yii2-authclient#31]
Some auth servers may not support refresh tokens. As said in [RFC](http://tools.ietf.org/html/rfc6749#section-1.5):
> Issuing a refresh token is optional at the discretion of the authorization server.

So in this case we need to change `refreshAccessToken` method of `OAuth2` class to not send such requests. Why not make this functionality optional (for example, check a config property in `BaseOAuth::restoreAccessToken` before trying to refresh token)?

**Comment by klimov-paul** [comment]
Resolved by commit 3837ed6526a3752b898be43586a738a19dbd9444
