### ISSUE TITLE
Creating different google login URLS in different machine

### ISSUE THREAD

**Issue by binishprabhakar** [yiisoft/yii2-authclient#317]
While clicking on the Sign in button it is producing two different URLs from differnt system

https://accounts.google.com/o/oauth2/auth/oauthchooseaccount - working fine
https://accounts.google.com/signin/v2/challenge/ - not working

Composer 
"yiisoft/yii2": "~2.0.39",
 "yiisoft/yii2-authclient": "^2.2",

Please help me to figure out this issue.

**Comment by samdark** [comment]
Would you please check if https://github.com/yiisoft/yii2-authclient/blob/97c51fa20227da6f0801dd893dacfe13872c5521/src/OAuth2.php#L72 is enabled in one case and disabled in another?
