### ISSUE TITLE
POST data in json or xml format to api client (e.g. Linkedin)

### ISSUE THREAD

**Issue by smorocho** [yiisoft/yii2-authclient#32]
I'm successfully authenticated using yii\authclient\clients\Linkedin
However the share endpoint on linkedin API requires a POST in XML or JSON (https://developer.linkedin.com/docs/share-on-linkedin)

    $data = ['comment' => 'Check out developer.linkedin.com! http://linkd.in/1FC2PyG', 'visibility'=>['code'=>'anyone'] ];
    try {
        $linkedin_response = $client->api('people/~/shares?format=json', 'POST', $data);
    } catch(\Exception $ex) {
        error_log("Linkedin error posting message: " . var_export($ex->getMessage(), true));
    }

I get the error:
`Linkedin error posting message: 'Request failed with code: 400, message: {\n  "errorCode": 0,\n  "message": "Couldn&#39;t parse share document: error: Unexpected end of file after null",\n  "requestId": "G0IMNTUPI7",\n  "status": 400,\n  "timestamp": 1435372342014\n}'`

Anyway there doesn't appear to be a way to override the Content-type: on POSTs effectively as they will get overwritten with composeRequestCurlOptions() in OAuth1.php or OAuth2.php will set the Content-type to application/x-www-form-urlencoded on a POST request.   And the $params sent to this function always assumes you want to POST via  http_build_query()   which won't work with JSON or XML

Is there a solution for this (I would like to make a pull request as I think I can probably come up with one).

**Comment by klimov-paul** [comment]
Duplicates #26

**Comment by smorocho** [comment]
This is solved with this pull request https://github.com/yiisoft/yii2-authclient/pull/33
