### ISSUE TITLE
cancelCallback in GitHub issue

### ISSUE THREAD

**Issue by SOHELAHMED7** [yiisoft/yii2-authclient#321]
### What steps will reproduce the problem?

When I try to login with GitHub OAuth 2

I click Cancel when scope/permission page is displayed with 2 buttons: "Cancel" and "Authorise (Allow)"

I click Cancel button

My `project/controllers/SiteController.php` file code:

```php
//...
class SiteController
{
    //...
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [            
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
                'cancelCallback' => [$this, 'onDenyCallback'],                
            ],
            // ...
        ];
    }

    public function onDenyCallback($client)
    {        
        Flash::error(Yii::t('app', 'Cannot connect because access to the account is denied. Please try again by allowing/granting the access'));
        return $this->redirect(['login']);
    }

    // ...

}
```

### What's expected?

Successful redirection to `login` path with error message in flash 

### What do you get instead?

404 error

### My debugging

This happens only with GitHub as far as I observed and in case of GitLab above issue is not reproduced and everything is working fine

When GitHub redirect back to our app after I click Cancel button, authclient=github in URL query param is not present and 404 is thrown from [`run()`](https://github.com/yiisoft/yii2-authclient/blob/master/src/AuthAction.php#L213)

When I set callback URL in GitHub web app: `https://example.com/site/auth?authclient=github`. Above issue is not reproduced and everything is working fine. (Here example.com is my app)

GitHub redirect to this URL of my app for e.g.

`https://example.com/web/site/auth?error=access_denied&error_description=The+user+has+denied+your+application+access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied&state=0fa77a01c9cd9d560e49639a06ef5041c7bf7b907e4bd1`

Here `authclient` is not present so `run()` throws 404 error.

Let me know if more info is needed.

I think there is something changed from GitHub side?

Also I think there  is no code change needed in this package to fix this issue but to add a note in docs about GitHub that in callback URL ("Authorization callback URL") add a URL query param `?authclient=github`

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.42.1
| Yii Auth Client version | ^2.2 (2.2.10)
| Yii HTTP Client version | 2.0.13
| PHP version             | 7.4.16
| Operating system        | Ubuntu

**Comment by samdark** [comment]
Interesting. Would you please create a pull request adjusting docs?

**Comment by SOHELAHMED7** [comment]
Yes. I am fine with creating PR and adjusting code. But I think we should double check before putting into docs. So if at least one other developer face same issue with GitHub, then adjust the docs. Let me know your thoughts.

**Comment by samdark** [comment]
Interesting. I've tried to reproduce the case with my apps and... I can't find a "Cancel" button :)

![image](https://user-images.githubusercontent.com/47294/120987362-31cd1100-c786-11eb-970b-d62111535cff.png)

**Comment by samdark** [comment]
I've reproduced this behavior so feel free to fix it or add to docs.
