### ISSUE TITLE
Disallowed_useragent on iOS

### ISSUE THREAD

**Issue by srakl** [yiisoft/yii2-authclient#353]
Hi, a few users have reported that they are getting a 403 Disallowed_useragent when trying to login using google.

I can't reproduce this as it works fone on my mobile (android), PC and Mac.

<a href="https://ibb.co/pLktcCh"><img src="https://i.ibb.co/pLktcCh/286023256-383238563781116-2528185337776724090-n.jpg" alt="286023256-383238563781116-2528185337776724090-n" border="0"></a>

any idea how to fix this or a workaround? Thanks

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version                 |  2.0.45 
| Yii Auth Client version      | 2.2.12.0 
| Yii HTTP Client version |
| PHP version              | 8.0.8
| Operating system         | Ubuntu

**Comment by bizley** [comment]
You need to check this Google's secure browsers policy because Yii is not doing anything on purpose here.
