### ISSUE TITLE
 PHP 8.1 Deprecated:  stripos(): Passing null to parameter #1 ... BaseOAuth.php on line 242

### ISSUE THREAD

**Issue by marty-macfly** [yiisoft/yii2-authclient#354]
When using yii2-auth with PHP 8.1, I've got the following deprecation warning:

```
PHP Deprecated:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /app/vendor/yiisoft/yii2-authclient/src/BaseOAuth.php on line 242
```

Message is due to the following part in the code:

```php
if (stripos($response->headers->get('content-type'), 'application/jwt') !== false) {
```
The get on header return null which was ok, before but is not anymore doing the following is fixing it:

```php
if (stripos($response->headers->get('content-type', ''), 'application/jwt') !== false) {
```

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.45
| Yii Auth Client version | 2.2.12
| Yii HTTP Client version | 2.0.14
| PHP version             | 8.1.8
| Operating system        |  Debian 11.4

**Comment by samdark** [comment]
Do you have some time for a pull request?

**Comment by marty-macfly** [comment]
Yes, I can submit one
