### ISSUE TITLE
SSO integration with login.microsoftonline.com not in login.live.com

### ISSUE THREAD

**Issue by ald3rson** [yiisoft/yii2-authclient#357]
### What steps will reproduce the problem?
Hello. Im developing an SSO for school / work email for microsoft. the problem is login.live.com is not redirecting me to login.microsoftonline.com. I did research that live.com is for personal use and work/school is for microsoftonline.com

So what I did is to change the yii2-client/authclient/src/client/Live.php

class Live extends OAuth2
{
    public $authUrl = 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize';
    public $tokenUrl = 'https://login.microsoftonline.com/common/oauth2/v2.0/token';
    public $apiBaseUrl = 'https://graph.microsoft.com/v1.0';

    public function init()
    {
        parent::init();
        if ($this->scope === null) {
            $this->scope = implode(',', [
                'User.Read',
            ]);
        }
    }
}
### What's expected?
Im expecting to run smoothly, 

### What do you get instead?
but errors were displayed.  Access token is empty.
<img width="1970" alt="Screen Shot 2022-08-05 at 10 19 03 AM" src="https://user-images.githubusercontent.com/13324608/182987741-308b5565-e8d5-4b2d-be1f-6a8186ce67c0.png">

This is my redirect URI in azure AD. the question mark '?' sign in the http://localhost/site/auth?authclient=live will not save in Azure AD so I change it to http://localhost/site/auth%3Fauthclient=live

<img width="1275" alt="Screen Shot 2022-08-05 at 10 30 26 AM" src="https://user-images.githubusercontent.com/13324608/182988969-3eb437b9-1363-4bca-b872-c8a8bd98cbd4.png">

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version            | 2.0
| Yii Auth Client version | 2.1
| Yii HTTP Client version | 1.1
| PHP version           | 7
| Operating system     | Windows Server 2012

**Comment by ald3rson** [comment]
Sorry, I just add this on the bottom yii2-client/authclient/src/client/Live.php  and it works.  
    protected function initUserAttributes()
    {
        return $this->api('me', 'GET');
    }
    public function applyAccessTokenToRequest($request, $accessToken)
    {
        $request->addHeaders(['Authorization' => 'Bearer '. $accessToken->getToken()]);
    }

**Comment by michael-schaefer-eu** [comment]
I thought that Microsoft does not support the _Live_ OAuth2 authentication method anymore?

When I open this [link](https://account.live.com/developers/applications) from the `Live` class, I get this error:

![Bildschirmfoto vom 2022-11-29 14-03-30](https://user-images.githubusercontent.com/9930093/204541384-63f09fc1-d384-4f75-9586-7af7d8e769eb.png)

Or is it only about the _App Registration_ ?

**Comment by edegaudenzi** [comment]
UPDATE: the [PR](https://github.com/yiisoft/yii2-authclient/pull/378) resolving this issue has been closed and **not** merged by @bizley with the following comment:

> Thank you for your contribution but unfortunately we are not adding any more clients. Please release it as a separate package.

Not sure why of this decision and as a result, we are not adding one of the most used external authentication providers, which would also make the plugin "business grade" (hence more popular), being Microsoft365 the reference for the vast majority of Companies around the globe.
Please @bizley give us a little bit more in-deep details if you can, so at least we can close down this issue as 'non-resolved'.

I will not release as a separate package: way too hassle for such a tiny thing, especially if there is already a solution made on purpose to host it.

@readers:  if you need this to authenticate your yii2 project against Microsoft365 to follow the normal yii\authclient\OAuth2 mechanism, you can still do that by taking 3 changes from [this commit](https://github.com/yiisoft/yii2-authclient/pull/378/commits/2d78ce5210347368ae1ae6850e0fcf4ad0c78b70):
- Updated asset picture with Microsoft365 Logo: src/assets/authchoice.png
- The extra CSS: src/assets/authchoice.css
- The main class: src/clients/Microsoft365.php

Live long and prosper \\\\//_

**Comment by bizley** [comment]
I'm understand the frustration but please try to look at this from the maintainers perspective. This is a [design decision](https://github.com/yiisoft/yii2/blob/master/docs/internals/design-decisions.md) made 9 years ago. Since then we don't accept new client implementations what you can verify by looking at the [not accepted PRs](https://github.com/yiisoft/yii2-authclient/pulls?q=is%3Apr+is%3Aclosed).

3rd-party-made extensions are more than welcome.

@ald3rson please follow the implementation and instructions provided kindly by @edegaudenzi , thank you.
