### ISSUE TITLE
Documentation mistak in sql for table auth 

### ISSUE THREAD

**Issue by devypt** [yiisoft/yii2-authclient#36]
sql code mentioned in documentation  for auth table
```
CREATE TABLE auth (
    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id int(11) NOT NULL,
    source string(255) NOT NULL,
    source_id string(255) NOT NULL
);
```
while it should replace string filed type with varchar and also fix alter
```
CREATE TABLE auth (
    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id int(11) NOT NULL,
    source varchar(255) NOT NULL,
    source_id varchar(255) NOT NULL
)
ALTER TABLE `auth` ADD INDEX ( `user_id` ) ;
ALTER TABLE `auth` ADD FOREIGN KEY ( `user_id` ) REFERENCES `user` (
`id`
) ON DELETE CASCADE ON UPDATE CASCADE ;

``````

https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/installation.md

**Comment by klimov-paul** [comment]
9c56e2a

**Comment by MaxFlower** [comment]
Do some changes for FOREIGN KEY and all will be ok. Little shorter.

CREATE TABLE auth (
    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id int(11) NOT NULL,
    source varchar(255) NOT NULL,
    source_id varchar(255) NOT NULL
);

ALTER TABLE auth ADD CONSTRAINT fkauthuser_iduserid
FOREIGN KEY auth(user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE;

**Comment by cebe** [comment]
@MaxFlower can you edit the file and send a pull request?

**Comment by MaxFlower** [comment]
Yes, I'll do it, @cebe

**Comment by cebe** [comment]
@MaxFlower it seems you have sent the pull request to your own repostiory. Can you open a new one against this repo?  `yiisoft/yii2-authclient` `master`

**Comment by MaxFlower** [comment]
@cebe Thank You) It was my mistake to sent the pull request to my own repo.
