### ISSUE TITLE
Facebook field list

### ISSUE THREAD

**Issue by master-7** [yiisoft/yii2-authclient#40]
Default return fields is a id, name - bug init 
https://github.com/yiisoft/yii2-authclient/blob/master/clients/Facebook.php#L66
Im fix 
/**
     * @inheritdoc
     */
    protected function initUserAttributes()
    {
        return $this->api('me?fields=id,name,email', 'GET');
    }

But this is a wrong solutions...

**Comment by samdark** [comment]
The right solution is to specify `email` in `scope`.

**Comment by master-7** [comment]
That is the problem.
Return values:
Array ( [name] => Nick Ovchinnikov [id] => 913960012004490 )
config:
'facebook' => [
                    'class'        => 'yii\authclient\clients\Facebook',
                    'clientId'     => '***',
                    'clientSecret' => '***',
                    'scope' => 'email'
                ],
And have not opportunities change this situation.
Vkontakte client have not this problem

**Comment by master-7** [comment]
View the function https://github.com/yiisoft/yii2-authclient/blob/master/clients/Facebook.php#L64
Problem is him

**Comment by samdark** [comment]
Right. In order to get more fields from `/me` call one should specify more fields like `/me?fields=name,email`.

@klimov-paul what do you think about introducing another public property called `$fields` and defaulting it to `name,email` for the purpose?

**Comment by master-7** [comment]
If to be exact required field
me?fields=id,first_name,last_name,email,gender

**Comment by master-7** [comment]
Good solutions in a Vkontakte client - https://github.com/yiisoft/yii2-authclient/blob/master/clients/VKontakte.php#L77

**Comment by samdark** [comment]
Yep, could be done alike.

**Comment by master-7** [comment]
Please, give me rights - im make fix.

**Comment by samdark** [comment]
Fixed.

**Comment by samdark** [comment]
@master-7 you don't have to have permissions: https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

**Comment by master-7** [comment]
Thanks you

**Comment by master-7** [comment]
Please, add to attributeNames array

public $attributeNames = [
        'id',
        'cover',
        'first_name',
        'last_name',
        'email',
        'gender'
    ];

**Comment by samdark** [comment]
Nope. Configure it yourself.

**Comment by nvthaovn** [comment]
It affects all recent app. Release 2.0.5, please !

**Comment by master-7** [comment]
This is the config
[code]
                'facebook' => [
                    'class'        => 'yii\authclient\clients\Facebook',
                    'clientId'     => '',
                    'clientSecret' => '',
                    'attributeNames' => ['id', 'cover', 'first_name', 'last_name', 'gender', 'email']
                ],
[/code]

**Comment by nvthaovn** [comment]
It's not working on 2.0.4 version

**Comment by master-7** [comment]
composer update

**Comment by nvthaovn** [comment]
of course, i updated. But the lastest version is 2.0.4.

**Comment by master-7** [comment]
It works for me...

**Comment by Philosoft** [comment]
@nvthaovn it works in `dev-master` for now. update package to that version
