### ISSUE TITLE
problem with OAuth1 class

### ISSUE THREAD

**Issue by Alien-Le** [yiisoft/yii2-authclient#41]
Some of web services seems to have more strict rules for getting the access token to access their services using Oauth1. They use the secret key received from the temporary token to create a key which is used as a part of the signature key to encrypt request for getting the access token. And despite there are some ambiguity in specification https://tools.ietf.org/html/rfc5849 they looks to be right in their solution.

**Comment by klimov-paul** [comment]
Relates #39

**Comment by umanamente** [comment]
Yeah, there is a problem, could you take a look?

**Comment by klimov-paul** [comment]
Resolved via #117
