### ISSUE TITLE
'email' cannot be null error when user disables email on Facebook auth

### ISSUE THREAD

**Issue by iadj** [yiisoft/yii2-authclient#44]
When a user tries to authenticate with Facebook but disables giving their email, the app returns the following error:
`exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null' in /vendor/yiisoft/yii2/db/Command.php:781`

After this error, the user can't authenticate anymore and the app always returns this error.

The app shouldn't try to create the account when email is null. It should return an error along with the ability to attempt authenticating again.

**Comment by samdark** [comment]
There's nothing about the handling in yii2-authclient itself. Check your app code.
