### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by v0lume** [yiisoft/yii2-authclient#48]
Maybe move SQL code for generating auth table to migration?

**Comment by klimov-paul** [comment]
The particular implementation for the auth data storage may vary depending on the particular project needs. Thus I can see no reson to provide migration file for this.
However current example at `docs\guide\installation.md` can be rewritten from plain SQL to migation code.

**Comment by klimov-paul** [comment]
Resolved by commit 2d4291b3944bfae20a976bfcaa25271b34056656
