### ISSUE TITLE
authclient not accept yii 2.0.6

### ISSUE THREAD

**Issue by mrbighokage** [yiisoft/yii2-authclient#51]
1) composer.json add
"yiisoft/yii2-authclient": "*" or "yiisoft/yii2-authclient": "~2.0.0" 
2) composer responce
Problem 1
    - yiisoft/yii2-authclient 2.0.5 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - yiisoft/yii2-authclient 2.0.4 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - yiisoft/yii2-authclient 2.0.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - yiisoft/yii2-authclient 2.0.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - yiisoft/yii2-authclient 2.0.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - yiisoft/yii2-authclient 2.0.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - Installation request for yiisoft/yii2-authclient * -> satisfiable by yiisoft/yii2-authclient[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].

Now i am copy to /vendor/yiisoft/yii2-authclient last release and ignore Problem 1

**Comment by klimov-paul** [comment]
It has nothing to do with 'yii' version - you must install CURL PHP extension.

**Comment by mrbighokage** [comment]
thanks
