### ISSUE TITLE
successCallback not being called

### ISSUE THREAD

**Issue by ramoscarlos** [yiisoft/yii2-authclient#53]
I use the authClient as specified at the quickstart guide (adding the action `auth` to actions and creating a `onAuthSuccess` function).

It seems to successfully log me in, since it redirects me to a page I want and gives me a `$code` variable as a `$_GET` parameter (that I assume it gets after successful login).

However, that controller does not take into account the `successCallback` function.

Is there a way I can trace why is the function after a successful callback is not being called?

**Comment by samdark** [comment]
Try XDebug.

**Comment by SivaRaman24** [comment]
For me also the same problem like above one existing for Google OAuth functionality. Am configured for Google Auth for the following
'google' => [
                    'class' => 'yii\authclient\clients\GoogleOAuth',
                    'clientId' => 'client_id', //client_id from google config
                    'clientSecret' => 'client_secret',  //clientSecret from google config
                    'returnUrl'=>'http://localhost/donationYii/index.php'
                ],

for google login alone successCallback not working, after the login it was redirected to http://localhost/donationYii/index.php?code=4/OgxBQI2DhoZ96vRBGooZBo1p2YFzRSOho4OfRIGRahA#

Can u please tell me what was the issue.

**Comment by klimov-paul** [comment]
> successCallback not being called

Unable to reproduce.

> For me also the same problem like above one existing for Google OAuth functionality. Am configured for Google Auth for the following

It is obvious you misunderstand `returnUrl` purpose. This parameter is used during OAuth workflow and should leadto the action, which will fetch access token.

You should use `successCallback` if you want user being redirected to a specific page after login.

**Comment by yurkinx** [comment]
I had the same problem:  I had `successCallback` for 2 scenarios - 
1. sign in with social id using controller function `userAuth`
2. attach social id to existing account on the settings page using controller function `userAttach`


 ```
public function actions()
    {
        return [
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'userAuth'],
            ],
            'attach' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'userAttach'],
            ],
        ];
    }
```

All social networks used proper successCallback except google. Google always redirected to `userAuth`
Apparently, when in config file we add returnUrl to google client (in my case `site/auth?authclient=google`),  that url is used each time as return url for google (obvious). I had to manually alter this returnUrl in beforeAction to solve the problem, here is the code:
```
public function beforeAction($action)
    {

        if($action->id == 'attach'){
            Yii::$app->authClientCollection->clients['google']->returnUrl=Url::to(['site/attach','authclient'=>'google'],true);
        }
        return parent::beforeAction($action); 
    }
```
