### ISSUE TITLE
OpenID discover method always returns 'No servers found!'

### ISSUE THREAD

**Issue by mehrna** [yiisoft/yii2-authclient#54]
I don't know what is the problem, but since my last update of yii2 project with composer the Open ID doesn't discover any server on my Open ID provider, however it was working very well before!
here is the provider address:
```php
http://www.samasoft.ir/SamaSSO/Account/LogOn
``` 
as of yii2 docs example:
```php
use yii\authclient\OpenId;

$client = new OpenId();
$client->authUrl = 'http://www.samasoft.ir/SamaSSO/Account/LogOn'; // Setup provider endpoint
$url = $client->buildAuthUrl(); // Get authentication URL
return Yii::$app->getResponse()->redirect($url); // Redirect to authentication URL
```
it returns :
```php
Exception (Exception) 'yii\base\Exception' with message 'No servers found!' 

in /var/www/SamaNext/vendor/yiisoft/yii2-authclient/OpenId.php:497
```
I don't know why? Is this my fault? or anything I have to do?

**Comment by samdark** [comment]
Try rolling version back. Does it help? If yes, try [`git bisect`](https://git-scm.com/docs/git-bisect) to find out exact commit that broke it.

**Comment by mehrna** [comment]
I tried rolling back. But the problem still there!

**Comment by samdark** [comment]
Then it's unlikely Yii problem. Either service you're trying to use changed or something else happened.

**Comment by mehrna** [comment]
Then how could I understand what is the problem? Could you please help me to find out the problem. It seems there is no change on the provider side too!

**Comment by samdark** [comment]
I'd help if it was likely Yii problem but it seems it's not based on what we've found so far.

**Comment by gonimar** [comment]
fresh installation
GoogleOpenId same problem

**Comment by samdark** [comment]
@gonimar can you check previous releases?

**Comment by gonimar** [comment]
Google has discontinued OpenID support and as of July 22nd 2015 has removed this endpoint.
https://developers.google.com/identity/protocols/OpenID2

**Comment by gonimar** [comment]
https://github.com/yiisoft/yii2-authclient/blob/master/clients/GoogleOpenId.php#L38

**Comment by samdark** [comment]
Original issue seems to be not about Google.

**Comment by gonimar** [comment]
У меня не работал именно GoogleOpenId поэтому к вопросу не относится

**Comment by klimov-paul** [comment]
`OpenId::discover()` is covered by unit tests:
https://github.com/yiisoft/yii2-authclient/blob/master/tests/OpenIdTest.php#L65
which are passing.
So unless more specific information is provided I can't see any issue here.
