### ISSUE TITLE
Twitter acount connect

### ISSUE THREAD

**Issue by lefteyecc-pu** [yiisoft/yii2-authclient#55]
Hello Everyone,

I'm trying to use Twitter oAuth and everything works until Twitter redirects back to my application. This is the error I receive:

# Exception – yii\base\Exception

#### 1. in /var/www/app/vendor/yiisoft/yii2-authclient/OAuth1.php

```php
 * @param array $params additional request params.
     * @return OAuthToken OAuth access token.
     * @throws Exception on failure.
     */
    public function fetchAccessToken(OAuthToken $requestToken = null, $oauthVerifier = null, array $params = [])
    {
        if (!is_object($requestToken)) {
            $requestToken = $this->getState('requestToken');
            if (!is_object($requestToken)) {
                throw new Exception('Request token is required to fetch access token!');

```

This occurs on line 124. Can anyone confirm this issue?

**Comment by thehiddennepali** [comment]
Same issue here

**Comment by voodoo-mobile** [comment]
Confirm

**Comment by thehiddennepali** [comment]
I am not sure this is some time of bug or not but may be we are using wrong method to achive our things, in my  I was willing to post on behalf of authenticated users so i need access token for authenticated user and surprisingly i found those details stored in private value in session and i get those value and it works for me, may be this could help you as well

**Comment by MaxFlower** [comment]
What we have in description: 
1. $requestToken = $oauthClient->fetchRequestToken(); // Get request token
2. * // After user returns at our site:
    * $accessToken = $oauthClient->fetchAccessToken($requestToken); // Upgrade to access token

and I think all right with logic, but here something strange->

**if (!is_object($requestToken)) **{
            $requestToken = $this->getState('requestToken');
            **if (!is_object($requestToken)) **{
                throw new Exception('Request token is required to fetch access token!');
            }
  }

Do You undestend that in your case (!is_object($requestToken) we will have executed both string 
$requestToken = $this->getState('requestToken');
and 
throw new Exception('Request token is required to fetch access token!');

$requestToken = $this->getState('requestToken') does not right, may be :)

**Comment by klimov-paul** [comment]
Unable to reproduce.
