### ISSUE TITLE
send twitter params

### ISSUE THREAD

**Issue by DrDeath72** [yiisoft/yii2-authclient#58]
need 
``` 
return $this->api('account/verify_credentials.json', 'GET', ['include_email' => 'true']);
```
instead
``` 
return $this->api('account/verify_credentials.json', 'GET');
```
how to?

**Comment by DrDeath72** [comment]
Чего никто не запилит передачу параметров для твитера?

**Comment by samdark** [comment]
Seems noone needs it yet besides you. A pull request would be handy.

**Comment by laziz-karimov** [comment]
Same here..., twitter has allowed to send user emails recently. It would be very helpful if we could get it

**Comment by samdark** [comment]
@laziz-karimov is it documented?

**Comment by DrDeath72** [comment]
@samdark https://dev.twitter.com/rest/reference/get/account/verify_credentials

**Comment by samdark** [comment]
Aha. There should be a way to request it but it should not be default.
