### ISSUE TITLE
Saving refresh token on authorization

### ISSUE THREAD

**Issue by iadj** [yiisoft/yii2-authclient#59]
I want to read & modify data on the user's social network that they connected with through `yii2-authclient`. Some networks' access tokens expire after a certain amount of time and require the supplied `refresh token` (retrieved when first authorizing an app) in order to get a new access token to read/modify user data. Is it possible to retrieve & save the `refresh_token` in yii2-authclient returned by an OAuth 2 network so that we can use the access/refresh tokens with the network's API?

**Comment by samdark** [comment]
Yes. Additional API calls are supported: https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/quick-start.md#getting-additional-data-via-extra-api-calls

**Comment by iadj** [comment]
Perfect @samdark, thank you!
