### ISSUE TITLE
Unused css class.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2-authclient#63]
https://github.com/yiisoft/yii2-authclient/blob/master/widgets/AuthChoice.php#L235

1. The "auth-clients" class seems to be added twice by default (once in the widget div, once in the ul).
2. The "clear" class has no associated css, so I think it's useless.

**Comment by samdark** [comment]
1. If we're gonna fix it, CSS should be adjusted as well since it's now for the case of two classes.
2. Indeed. Could be removed.

**Comment by samdark** [comment]
@klimov-paul what was the idea behind these?

**Comment by klimov-paul** [comment]
I don't really remember. The origianal markup of the widget was created as draft. Once there was a issue for for its adjustment:
https://github.com/yiisoft/yii2/issues/1653

However, it it was closed eventually without fix.

Most likely current style schema is a mistake, which has been not noticed. However changing it now actually breaks a BC for any custom CSS applied for the widget.

**Comment by SamMousa** [comment]
How about adding something like a @deprecated comment and so you can queue it for removal?

Note that the BC break would be minor, and you could even choose to just upgrade the major version if you feel the BC break warrants it. (I know Yii itself doesn't use Semantic Versioning, but for a smaller project /part like this, it would be relatively easy to switch).

This way people will not automatically get it unless explicitly requested.
(I feel the BC break is small enough to not increment the major version though, since it is very unlikely that a break will result in loss of functionality, instead of just a minor visual bug).

Also note that from that reasoning any change in HTML structure could be a BC break since people might have JS / CSS selectors that depend on it. -- The question then becomes, what part of the HTML structure is actually part of the public API

**Comment by samdark** [comment]
I think it could be changed.

**Comment by klimov-paul** [comment]
Resolved by commit 3637296694338ceab769aa16541f2117c45c5734
