### ISSUE TITLE
Cannot override width and height of Facebook popup

### ISSUE THREAD

**Issue by mfrsousa** [yiisoft/yii2-authclient#64]
//config/web.php 
    'clients'=>[
        'facebook' => [
            ...
           'viewOptions'    => [
               'popupWidth'  => 1200,
               'popupHeight' => 800,
               'widget' => [
                  'class'       => 'app\widgets\AuthChoiceItem',
             ],
          ],

**Comment by umanamente** [comment]
So as of any other auth clients. There are fixed dimensions in [/blob/master/assets/authchoice.js](https://github.com/yiisoft/yii2-authclient/blob/master/assets/authchoice.js#L23)

**Comment by SilverFire** [comment]
The line you're pointing to is just a default.

We can introduce `clientOptions` property and pass them to the JS to override defaults
https://github.com/yiisoft/yii2-authclient/blob/master/widgets/AuthChoice.php#L252

**Comment by klimov-paul** [comment]
Each client can setup its own view options. `popupWidth` and `popupHeight` are correctly respected by  `AuthChoice` widget.

Now, lets have a look at your config:

```
'viewOptions'    => [
           'popupWidth'  => 1200,
           'popupHeight' => 800,
           'widget' => [
              'class'       => 'app\widgets\AuthChoiceItem', // ???
         ],
      ],
```

Where you get this noncence?
If there is a `widget` option specified `AuthChoice` will NOT render link for the client and will NOT attach any JavaScrip code for it, leaving everything to the specified widget.

No wonder it does not work.
