### ISSUE TITLE
This authorization code has been used.

### ISSUE THREAD

**Issue by rajvanshipradeep15** [yiisoft/yii2-authclient#65]
I get this error when I am using facebook client to login.
This is the error I get.

Exception – yii\authclient\InvalidResponseException
Request failed with code: 400, message: {"error":{"message":"This authorization code has been used.","type":"OAuthException","code":100,"fbtrace_id":"CKSTHLF8PgK"}}

I googled this issue and found that we cannot send request to get access token twice.

**Comment by samdark** [comment]
So what this has to do with authclient?

**Comment by rajvanshipradeep15** [comment]
I guess we are trying to access the token twice in the authclient,

**Comment by samdark** [comment]
I can't reproduce it on my projects using authclient and Facebook auth.

**Comment by rajvanshipradeep15** [comment]
Samdark can you please check this image and guide me if I am doing any mistake.


![exception](https://cloud.githubusercontent.com/assets/3005720/11335326/72e98d00-9201-11e5-8412-f525930ede53.png)

**Comment by samdark** [comment]
The image doesn't give me enough info to get an idea on why it fails.

**Comment by rajvanshipradeep15** [comment]
Hello Samdark, thank you for your support I figured it out.

**Comment by SilverFire** [comment]
Could you share your experience to community, please?

**Comment by rajvanshipradeep15** [comment]
In the function onAuthSuccess, the object auth tries to create user again.
This is what I modified.
//$user = $auth->user;
$objUser = new User();
