### ISSUE TITLE
Error on using sendRequest function to do a PUT request with data in the request body

### ISSUE THREAD

**Issue by cyberinferno** [yiisoft/yii2-authclient#68]
PHP throws curl_setopt() array to string conversion error if PUT request with data in the body is done using the function sendRequest function found in OAuth class.

**Comment by samdark** [comment]
Please provide some code to reproduce it.

**Comment by cyberinferno** [comment]
```PHP
$params = ['name' => 'John Doe', 'email' => 'john@doe.com']; // Data to be sent
$response = $this->sendRequest('PUT', $url, $params, ['Authorization: Bearer 7df54sad0vdr3jvcnfgn3n4mndfghjh45jhjwqwehjj']); // PUT request code which threw error
```

**Comment by klimov-paul** [comment]
Unable to reproduce. 
Params are passed via `CURLOPT_POSTFIELDS`, which is according to the php.net documentation allows to be an array:

> Passing an array to CURLOPT_POSTFIELDS will encode the data as multipart/form-data, while passing a URL-encoded string will encode the data as application/x-www-form-urlencoded. 

There must be something wrong with the CURL library you use.
