### ISSUE TITLE
AuthAction: cannot get refresh_token with GoogleOAuth

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2-authclient#76]
Google will only send a *refresh_token* on the very first authorization and then never again. On any subsequent authorization only an *id_token* is sent which cannot be used to acquire a new access token once the old one has expired. This is a show-stopper when attempting to acquire the refresh token from users who have already been authorized in case something went wrong and the refresh token was not permanently stored. There are only two ways around this:

* Ask your users to revoke access to your app in their Google account and try again (unrealistic), or
* Sending an extra parameter ```approval_prompt``` to ```force```. More info on the topic [here](http://stackoverflow.com/a/10857806).

Using the *approval_prompt* parameter is however currently unsupported by the GoogleOAuth client.

**Comment by vercotux** [comment]
The problem lies in AuthAction. It should be possible to somehow specify additional parameters to *buildAuthUrl()*, which is being [called without any arguments](https://github.com/yiisoft/yii2-authclient/blob/ea26bd03c622a968c02c7e58a3ecae977a90ccf4/AuthAction.php#L366).

**Comment by vercotux** [comment]
I ended up overriding *authOAuth2($client)* in AuthAction. Here is the code:

```PHP
protected function authOAuth2($client, $tokenParams = [], $urlParams = [])
{
	if (isset($_GET['error'])) {
		if ($_GET['error'] == 'access_denied') {
			// user denied error
			return $this->redirectCancel();
		} else {
			// request error
			if (isset($_GET['error_description'])) {
				$errorMessage = $_GET['error_description'];
			} elseif (isset($_GET['error_message'])) {
				$errorMessage = $_GET['error_message'];
			} else {
				$errorMessage = http_build_query($_GET);
			}
			throw new Exception('Auth error: ' . $errorMessage);
		}
	}
	// Get the access_token and save them to the session.
	if (isset($_GET['code'])) {
		$code = $_GET['code'];
		$token = $client->fetchAccessToken($code,$tokenParams);
		if (!empty($token)) {
			return $this->authSuccess($client);
		} else {
			return $this->redirectCancel();
		}
	} else {
		$url = $client->buildAuthUrl($urlParams);
		return Yii::$app->getResponse()->redirect($url);
	}
}
```

I wish there was a more elegant way to do this.

**Comment by klimov-paul** [comment]
You may add any GET paramter to `OAuth2::authUrl`:

```php
'googleOAuth' => [
    'class' => 'yii\authclient\clients\GoogleOAuth',
    'authUrl' => 'https://accounts.google.com/o/oauth2/auth?access_type=offline',
    'clientId' => '???',
    'clientSecret' => '???',
],
```

This works fine without any code overriding.

**Comment by vercotux** [comment]
Tested authUrl and the trick you presented indeed works.

You missed the second part of the modification though (which is heavily related to this issue, so I dont think it needs a whole new issue) about adding additional tokenParams to fetchAccessToken. There does not seem to be a way to add for example ```'redirect_uri'=>'postmessage'``` to the request, which is [required by Google to enable the one-time-code flow](https://developers.google.com/identity/sign-in/web/server-side-flow#step_4_add_the_sign-in_button_to_your_page).

**Comment by klimov-paul** [comment]
>There does not seem to be a way to add for example 'redirect_uri'=>'postmessage' to the token request

There is `BaseOAuth::returnUrl`, you can set it to `postmessage` value just the same way.
By the way, it seems you should use `GoogleHybrid` instead `GoogleOAuth` for your goal.

**Comment by vercotux** [comment]
Possible. It has been a while since I've used yii2-authclient, so I need to look into it again. Thank you for the useful hints.

**Comment by nexen2** [comment]
To get refresh token on first login you need to set "?access_type=offline" in "authUrl". And then save it somewhere, in database, files etc.
If you have no database or if you ok with prompting access rights every time on login in you can add "&approval_prompt=force" to same URL. Thats will enforce Google send you refresh token every time you are logging in, but also enforces showing access rights prompt every time.

`
class MyGoogleClient extends yii\authclient\clients\Google
{

    /**
     * Set to true if you want to get refresh token always on login
     * @var type
     */
    public $enforceRefreshToken = false;

    /**
     * {@inheritdoc}
     */
    public function init()
    {
        parent::init();

        if (is_array($this->scope)) {
            $this->scope = implode(' ', $this->scope);
        }

        $additionalParams = [];
        if ($this->autoRefreshAccessToken) {
            $additionalParams['access_type'] = 'offline';
        }
        if ($this->enforceRefreshToken) {
            $additionalParams['approval_prompt'] = 'force';
        }
        if (!empty($additionalParams)) {
            $this->authUrl = $this->composeUrl($this->authUrl, $additionalParams);
        }
    }
    /**
     * {@inheritdoc}
     * @return string return URL.
     */
    protected function defaultReturnUrl()
    {
        return Yii::$app->getUrlManager()->createAbsoluteUrl([Yii::$app->controller->getRoute(), 'authclient' => 'google']);
    }
}
`
