### ISSUE TITLE
Add configurable $baseUrl parameter

### ISSUE THREAD

**Issue by umanamente** [yiisoft/yii2-authclient#77]
Assume there are multiple domains for an OAuth provider (like in wikipedia):
```
https://en.wikipedia.org/wiki/Special:OAuth
https://ru.wikipedia.org/wiki/Special:OAuth
... etc
```
So there have to be the choice to pick one:
```php
public $baseUrl;
public $authUrl = '/initiate?format=json&oauth_callback=oob';
```

Maybe use overridable getters instead of `$this->authUrl`?

**Comment by klimov-paul** [comment]
See explanations at #78
