### ISSUE TITLE
OAuthToken not compatible with Google's access token

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2-authclient#82]
By default [OAuthToken](http://www.yiiframework.com/doc-2.0/yii-authclient-oauthtoken.html) expects: 
* [$tokenParamKey](http://www.yiiframework.com/doc-2.0/yii-authclient-oauthtoken.html#$tokenParamKey-detail) to be [```'oauth_token'```](https://github.com/yiisoft/yii2-authclient/blob/c25b04a34ab1b9ae4f2f7a35aeee38033ad3654d/OAuthToken.php#L32)
* [$tokenSecretParamKey](http://www.yiiframework.com/doc-2.0/yii-authclient-oauthtoken.html#$tokenSecretParamKey-detail) to be [```'oauth_token_secret'```](https://github.com/yiisoft/yii2-authclient/blob/c25b04a34ab1b9ae4f2f7a35aeee38033ad3654d/OAuthToken.php#L36)

Meanwhile Google's OAuthToken consists of the following parameters
* **access_token** *The token that can be sent to a Google API.*
* **refresh_token** *A token that may be used to obtain a new access token. Refresh tokens are valid until the user revokes access. This field is only present if access_type=offline is included in the authorization code request.*
* **expires_in** *The remaining lifetime of the access token.*
* **token_type** *Identifies the type of token returned. At this time, this field will always have the value Bearer.*

How is [getToken()](http://www.yiiframework.com/doc-2.0/yii-authclient-oauthtoken.html#getToken%28%29-detail) for example supposed to return 'access_token' when it looks for 'oauth_token' instead? Am I missing something obvious here?

**Comment by klimov-paul** [comment]
`AccessToken` works jsut fine. It is proper configured for OAuth2 flow:
https://github.com/yiisoft/yii2-authclient/blob/master/OAuth2.php#L187

**Comment by vercotux** [comment]
You're right. I must have done something else wrong to hit an issue with this. Sorry for the inconvenience.

**Comment by vercotux** [comment]
Hang on, what about **refresh_token**, **id_token** and **token_type**. Those 3 are still missing.
