### ISSUE TITLE
Cannot upload a file to facebook

### ISSUE THREAD

**Issue by traykovn** [yiisoft/yii2-authclient#83]
I tried to upload a file to a facebook page. Currently facebook allows two ways to do that: thought the URL of an image that's on the web; through a file upload. 

The file upload requires multipart/form-data header, which is set if you add CURLFile object to the parameters of the request (or if you put '@' before the value of the param before PHP 5.6). 

Currently this is not working. Even if I put CURLOPT_POSTFIELDS with CURLFile as a param, before sending the request through setCurlOptions, I am not able to upload a photo, because my parameters are overriden in composeRequestCurlOptions. I can override this method and change what needed, but I don't think my parameters should be overwritten by default.

My code:

```
$response = $this->facebook->api("$this->facebookPageId/photos", 'POST', [
   'source' => new \CURLFile($post->photo->mainFilepath),
   'caption' => $post->caption,
]);
```

Thanks for the plugin!

**Comment by klimov-paul** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/6961
