### ISSUE TITLE
Is there a way to invalidate a previously authenticated client?

### ISSUE THREAD

**Issue by kategee** [yiisoft/yii2-authclient#94]
I'm restricting Google auth2 to a certain domain, so if someone logs in with an unauthorized e-mail address the authentication is successful from authclient's point of view, but I need to invalidate it but I'm not seeing any methods that would enable me to do that.

**Comment by klimov-paul** [comment]
@kategee, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
