### ISSUE TITLE
redirect_uri duplicate GET params. Google Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by freask** [yiisoft/yii2-authclient#95]
I have url http://mysite.com/user/auth/index?authclient=google
This url redirects to Google with error:

Error: redirect_uri_mismatch
The redirect URI in the request: htt p://mysite.com/user/auth/index?**%2Fuser%2Fauth%2Findex=&amp;**authclient=google did not match a registered redirect URI.

redirect_uri is wrong.
It should be http://mysite.com/user/auth/index?authclient=google (without additional duplicated params)

function yii\authclient\OAuth2->defaultReturnUrl() make something wrong;

**Comment by samdark** [comment]
Are you able to reproduce it with a clean basic application template? If yes, how exactly?

**Comment by freask** [comment]
Sorry but i have not time for this)
I can write my web.php config to issue if it can help


>Пятница, 18 марта 2016, 16:06 +03:00 от Alexander Makarov <notifications@github.com>:
>
>Are you able to reproduce it with a clean basic application template? If yes, how exactly?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly or  view it on GitHub


С уважением,
Кашин Александр
freask@mail.ru

**Comment by samdark** [comment]
It could help. We can't solve it if we can't reproduce it.

**Comment by freask** [comment]
This is web.php

$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'components' => [
        'request' => [
            'cookieValidationKey' => 'xxxxxxxxxxx',
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
                ],
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],

        'user' => [
            'identityClass' => 'budyaga\users\models\User',
            'enableAutoLogin' => true,
            'loginUrl' => ['/login'],
        ],
        
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => true,
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => require(__DIR__ . '/db.php'),
        
        'authClientCollection' => [            
            'class' => 'yii\authclient\Collection',
            'clients' => [
               'google' => [
                   'class' => 'budyaga\users\components\oauth\Google',
                   'clientId' => 'xxx',
                   'clientSecret' => 'xxxxx',
                ],
            ],
        ],
        
        'authManager' => [
            'class' => 'yii\rbac\DbManager',
            'cache' => 'cache', //Включаем кеширование
        ],
        
        'urlManager' => [
            'class' => 'yii\web\UrlManager',
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            //'enableStrictParsing' => true,
            'rules' => [
                '/login' => '/user/user/login',
                '/logout' => '/user/user/logout',
                '/contact' => '/site/contact',
                '/profile' => '/user/user/profile',
                '/alphaTest' => '/site/alpha-test',
                '/user/user/uploadPhoto' => '/user/user/upload-photo',                               
                '/unbind/<id:[\w\-]+>' => '/user/auth/unbind',
                '/wrongEmail' => '/user/auth/wrong-email',                
                '/user/<id:\d+>' => '/user/user/view',            
                '<controller:\w+>'=>'<controller>/index',
                '<action:\w+>'=>'site/<action>',               
                '<controller:\w+>/<id:\d+>' => '<controller>/view',           
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
                '<module:\w+>/<controller:\w+>/<action:\w+>/<id:\d+>' => '<module>/<controller>/<action>',
                '<module:\w+>/<controller:\w+>/<action:\w+>' => '<module>/<controller>/<action>',
                '<module:\w+>/<controller:\w+>' => '<module>/<controller>/index', 
            ], 
        ],
        
        'i18n' => [
            'translations' => [
                'users*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@budyaga/users/messages',
                    'forceTranslation' => true,
                    'fileMap' => [
                        'users' => 'users.php'
                    ]
                ]
            ]
        ]
    ],
    
    'modules' => [
        'user' => [
            'class' => 'budyaga\users\Module',
        ],
        'api' => [
            'class' => 'app\modules\api\Module',
        ],      
    ],
    'params' => $params,
];

**Comment by samdark** [comment]
You're using custom `budyaga\users\components\oauth\Google`. Can you try with stock Google auth class?

**Comment by freask** [comment]
I solved it
It was because wrong .htaccess
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)\?*$ index.php/$1 [L,QSA]

It works fine, if i change last string to 
RewriteRule . index.php
