### ISSUE TITLE
Curl error requesting  Failed to connect to graph.facebook.com port 443: No route to host

### ISSUE THREAD

**Issue by chiragspaceo** [yiisoft/yii2-authclient#96]
Login with facebook

I'm trying to implement facebook Login in my website that is written in Yii2 using Yii2-authclient. but sometimes I am getting below exception that:

Curl error requesting "https://graph.facebook.com/oauth/access_token": #7 - Failed to connect to graph.facebook.com port 443: No route to host

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.3 
| PHP version     | 5.5.9
| Operating system  | ubuntu

**Comment by SilverFire** [comment]
The problem is related to your networking, not to Yii or OAuth.
No route to host means, that your server does not have connection or route to default gateway.
