### ISSUE TITLE
Specifically target links inside AuthChoice widget

### ISSUE THREAD

**Issue by justinvoelker** [yiisoft/yii2-authclient#98]
When using the AuthChoice widget, all anchor tags are targets and treated as auth links.  While the reasoning behind this is understandable, it makes it difficult to treat some auth links differently.  For instance, in the example code below, the auth choices for a user offer the ability to either connect or disconnect an external account.

```
foreach ($authAuthChoice->getClients() as $client) {
    $clientName = $client->getName();
    if (in_array($clientName, $model->connectedAuthClients)) {
        echo Html::a('Disconnect ' . $clientName, ['auth-client-disconnect', 'authclient' => $clientName]);
    } else {
        $authAuthChoice->clientLink($client, 'Connect ' . $client->getName());
    }
    echo '<br>';
}
```

Rather than targeting all anchor tags in the authchoice.js, it would be great to only target those with the default class of `auth-link`.  This would allow the standard auth choice links to continue to function as intended while allowing for custom links to following their standard behavior.

**Comment by klimov-paul** [comment]
Duplicates #37
